"use client";

import { Radio, RefreshCw, ChevronLeft } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";

const TOP_LEAGUES = [
  { key: "Iran", flag: "🇮🇷", title: "ایران", names: ["Persian Gulf Pro League", "Iranian Pro League", "خلیج فارس"], countries: ["iran"] },
  { key: "Spain", flag: "🇪🇸", title: "اسپانیا", names: ["La Liga", "Laliga"], countries: ["spain"] },
  { key: "England", flag: "🏴", title: "انگلیس", names: ["Premier League"], countries: ["england", "united kingdom"] },
  { key: "France", flag: "🇫🇷", title: "فرانسه", names: ["Ligue 1"], countries: ["france"] },
  { key: "Italy", flag: "🇮🇹", title: "ایتالیا", names: ["Serie A"], countries: ["italy"] },
  { key: "Germany", flag: "🇩🇪", title: "آلمان", names: ["Bundesliga"], countries: ["germany"] },
  { key: "Netherlands", flag: "🇳🇱", title: "هلند", names: ["Eredivisie"], countries: ["netherlands", "holland"] },
  { key: "Saudi Arabia", flag: "🇸🇦", title: "عربستان", names: ["Saudi Pro League", "Saudi Professional League"], countries: ["saudi arabia"] },
  { key: "Qatar", flag: "🇶🇦", title: "قطر", names: ["Qatar Stars League", "Stars League"], countries: ["qatar"] },
  { key: "Turkey", flag: "🇹🇷", title: "ترکیه", names: ["Süper Lig", "Super Lig"], countries: ["turkey", "türkiye"] },
  { key: "Europe", flag: "🇪🇺", title: "لیگ قهرمانان اروپا", names: ["UEFA Champions League", "Champions League"], countries: ["europe", "world"] },
  { key: "Asia", flag: "🌏", title: "لیگ قهرمانان آسیا", names: ["AFC Champions League Elite", "AFC Champions League", "AFC Champions League Two"], countries: ["asia", "world"] },
];

const TEAM_FA = { "Manchester City": "منچسترسیتی", "Manchester United": "منچستریونایتد", Liverpool: "لیورپول", Arsenal: "آرسنال", Chelsea: "چلسی", Tottenham: "تاتنهام", "Real Madrid": "رئال مادرید", Barcelona: "بارسلونا", "Atletico Madrid": "اتلتیکومادرید", "Bayern Munich": "بایرن مونیخ", "Borussia Dortmund": "بوروسیا دورتموند", Juventus: "یوونتوس", Inter: "اینتر", "AC Milan": "آث میلان", PSG: "پاری‌سن‌ژرمن", Tractor: "تراکتور", Persepolis: "پرسپولیس", Esteghlal: "استقلال", Sepahan: "سپاهان" };
const faTeam = (name) => TEAM_FA[name] || name;
const normalize = (value) => String(value || "").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();
const isLive = (m) => ["1H", "HT", "2H", "ET", "P", "BT", "LIVE", "IN PLAY"].includes(String(m?.statusShort || m?.status || "").toUpperCase());
const leagueInfo = (m) => TOP_LEAGUES.find((l) => l.names.some((n) => normalize(n) === normalize(m?.league)) && l.countries.some((c) => normalize(m?.country).includes(c))) || null;

function valueOf(stats, labels) { const item = (stats || []).find((s) => labels.some((x) => normalize(s?.type).includes(normalize(x)))); return item?.value ?? "—"; }
function StatStrip({ stats }) { const home = stats?.[0]?.statistics || []; const away = stats?.[1]?.statistics || []; const items = [["مالکیت", valueOf(home, ["ball possession"]), valueOf(away, ["ball possession"])], ["شوت", valueOf(home, ["total shots"]), valueOf(away, ["total shots"])], ["در چارچوب", valueOf(home, ["shots on goal"]), valueOf(away, ["shots on goal"])], ["کرنر", valueOf(home, ["corner kicks"]) , valueOf(away, ["corner kicks"])]]; return <div className="mt-2.5 grid grid-cols-4 gap-1 rounded-xl border border-white/6 bg-black/10 p-1.5">{items.map(([label, h, a]) => <div key={label} className="rounded-lg bg-white/[.025] px-1 py-2 text-center"><div className="text-[7px] font-bold text-slate-600">{label}</div><div className="mt-1 text-[9px] font-black text-slate-200 tabular-nums"><span>{h}</span><span className="mx-1 text-slate-700">·</span><span>{a}</span></div></div>)}</div>; }
function MatchRow({ match }) { const league = leagueInfo(match); return <Link href={match.id ? `/matches/${match.id}` : "/matches"} className="group block rounded-2xl border border-red-400/15 bg-red-500/[.035] p-3 transition active:scale-[.99] hover:border-red-300/25"><div className="mb-2 flex items-center justify-between gap-2"><div className="flex min-w-0 items-center gap-1.5 text-[8px] font-black text-slate-400"><span className="text-sm leading-none">{league?.flag || "⚽"}</span><span className="truncate">{league?.title || match.league}</span></div><span className="shrink-0 rounded-full bg-red-500/10 px-2 py-1 text-[7px] font-black text-red-300">● LIVE{match.elapsed ? ` · ${match.elapsed}'` : ""}</span></div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><div className="truncate text-right text-[10px] font-black text-slate-100">{faTeam(match.home)}</div><div className="min-w-[62px] text-center text-base font-black tabular-nums text-white">{match.homeScore ?? "—"} <span className="text-slate-600">-</span> {match.awayScore ?? "—"}</div><div className="truncate text-left text-[10px] font-black text-slate-100">{faTeam(match.away)}</div></div><StatStrip stats={match.stats} /><div className="mt-2 flex items-center justify-between text-[8px] font-bold text-slate-600"><span>آمار زنده مسابقه</span><ChevronLeft size={12} className="transition-transform group-hover:-translate-x-0.5"/></div></Link>; }

export default function HomeLiveMatches() {
  const [matches, setMatches] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = async (manual = false) => { if (manual) setRefreshing(true); try { const res = await fetch("/api/football/live", { cache: "no-store" }); const json = await res.json(); const live = (Array.isArray(json.matches) ? json.matches : []).map((m) => ({ ...m, topLeague: leagueInfo(m) })).filter((m) => m.topLeague && isLive(m)); const enriched = await Promise.all(live.slice(0, 12).map(async (m) => { try { const r = await fetch(`/api/football/fixture?id=${encodeURIComponent(m.id)}&section=statistics`, { cache: "no-store" }); const j = await r.json(); return { ...m, stats: Array.isArray(j.data) ? j.data : [] }; } catch { return { ...m, stats: [] }; } })); setMatches(enriched); } catch { setMatches([]); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { load(); const timer = setInterval(() => load(), 30000); return () => clearInterval(timer); }, []);
  return <section className="rounded-3xl border border-white/8 bg-gradient-to-br from-red-500/[.055] via-white/[.025] to-transparent p-3.5 shadow-xl"><div className="mb-3 flex items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><Radio size={15} className="text-red-300"/><h2 className="text-sm font-black">مرکز زنده · ۱۲ لیگ منتخب</h2><span className="rounded-full bg-red-500/10 px-2 py-0.5 text-[7px] font-black text-red-300">LIVE</span></div><p className="mt-1 truncate text-[9px] font-bold text-slate-600">ایران · اسپانیا · انگلیس · فرانسه · ایتالیا · آلمان · هلند · عربستان · قطر · ترکیه · اروپا · آسیا</p></div><button onClick={() => load(true)} className="shrink-0 rounded-xl border border-white/8 bg-white/[.03] p-2 text-slate-500 transition hover:text-slate-200" aria-label="به‌روزرسانی"><RefreshCw size={14} className={refreshing ? "animate-spin" : ""}/></button></div>{loading ? <div className="h-24 animate-pulse rounded-2xl bg-white/[.035]"/> : matches.length ? <div className="space-y-2.5">{matches.map((m) => <MatchRow key={m.id} match={m}/>)}</div> : <div className="rounded-2xl border border-white/7 bg-white/[.02] px-4 py-7 text-center"><Radio size={19} className="mx-auto text-slate-700"/><p className="mt-2 text-[10px] font-black text-slate-500">در حال حاضر مسابقه زنده‌ای از ۱۲ لیگ منتخب نداریم</p><p className="mt-1 text-[8px] text-slate-700">سیستم هر ۳۰ ثانیه دوباره بررسی می‌کند</p></div>}</section>;
}
