"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowRight, CalendarDays, Clock3, Radio, RefreshCw, Star, Trophy } from "lucide-react";
import { useSearchParams } from "next/navigation";
import HomeLiveMatches from "../components/HomeLiveMatches";

const SETTINGS_KEY = "fot10-settings";
function readSettings() { try { return { autoRefresh: true, compactScores: true, ...JSON.parse(localStorage.getItem(SETTINGS_KEY) || "{}") }; } catch { return { autoRefresh: true, compactScores: true }; } }
function iranDate(offset = 0) { const now = new Date(); const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(now).reduce((a, p) => ({ ...a, [p.type]: p.value }), {}); const d = new Date(`${parts.year}-${parts.month}-${parts.day}T12:00:00+03:30`); d.setDate(d.getDate() + offset); return d.toISOString().slice(0, 10); }
function toTime(value) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleTimeString("fa-IR", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "Asia/Tehran" }); }
function mapGame(match) { const statusCode = String(match.statusShort || match.status || "").toUpperCase(); const live = ["1H", "HT", "2H", "ET", "P", "BT", "LIVE", "IN PLAY"].includes(statusCode); const finished = ["FT", "AET", "PEN"].includes(statusCode); return { ...match, league: match.league || "مسابقات فوتبال", home: match.home || "میزبان", away: match.away || "مهمان", minute: live && match.elapsed ? `${match.elapsed}'` : finished ? "پایان" : toTime(match.date), live, finished }; }

export default function MatchesPage() {
  const searchParams = useSearchParams();
  const liveOnly = searchParams.get("live") === "1";
  const [games, setGames] = useState([]); const [day, setDay] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false); const [settings, setSettings] = useState({ autoRefresh: true, compactScores: true });
  const date = useMemo(() => iranDate(day), [day]);
  useEffect(() => { const sync = () => setSettings(readSettings()); sync(); window.addEventListener("storage", sync); window.addEventListener("fot10-settings-changed", sync); return () => { window.removeEventListener("storage", sync); window.removeEventListener("fot10-settings-changed", sync); }; }, []);
  const loadMatches = useCallback(async ({ manual = false } = {}) => { if (manual) setRefreshing(true); setLoading(true); setError(""); try { const endpoint = liveOnly ? "/api/football/live" : `/api/football/fixtures?date=${date}`; const response = await fetch(endpoint, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "دریافت مسابقات ناموفق بود"); const source = Array.isArray(payload.matches) ? payload.matches : []; setGames(source.map(mapGame).filter((g) => liveOnly ? g.live : true)); } catch (err) { setGames([]); setError(err?.message || "اتصال داده زنده برقرار نشد."); } finally { setLoading(false); setRefreshing(false); } }, [date, liveOnly]);
  useEffect(() => { loadMatches(); }, [loadMatches]);
  useEffect(() => { if (!settings.autoRefresh) return; const timer = setInterval(() => loadMatches(), 30000); return () => clearInterval(timer); }, [loadMatches, settings.autoRefresh]);
  const liveCount = games.filter((g) => g.live).length; const grouped = games.reduce((acc, g) => { const key = g.country ? `${g.country} · ${g.league}` : g.league; (acc[key] ||= []).push(g); return acc; }, {}); const dayLabel = day === -1 ? "دیروز" : day === 1 ? "فردا" : "امروز";
  return <main className="fot-shell"><div className="fot-container space-y-5">
    <header className="flex items-center justify-between"><div className="flex items-center gap-3"><Link href="/" className="glass h-10 w-10 rounded-xl grid place-items-center"><ArrowRight size={19}/></Link><div><h1 className="text-xl font-black">{liveOnly ? "مرکز زنده" : "مرکز بازی‌ها"}</h1><p className="text-[11px] text-slate-500">{liveOnly ? "تمام مسابقات در حال برگزاری" : "نتایج واقعی و زنده فوتبال"}</p></div></div><button onClick={() => loadMatches({ manual: true })} className="glass h-10 w-10 rounded-xl grid place-items-center" aria-label="به‌روزرسانی"><RefreshCw size={18} className={refreshing ? "animate-spin" : ""}/></button></header>
    {!liveOnly && <HomeLiveMatches />}
    {liveOnly ? <section className="rounded-3xl border border-red-400/15 bg-gradient-to-br from-red-500/[.07] via-white/[.025] to-transparent p-4 shadow-xl"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Radio size={18} className="text-red-300"/><h2 className="text-base font-black">نبض زنده فوتبال</h2><span className="rounded-full bg-red-500/10 px-2 py-1 text-[8px] font-black text-red-300">LIVE</span></div><p className="mt-1 text-[9px] text-slate-500">بازی‌ها هر ۳۰ ثانیه تازه می‌شوند؛ فقط داده تأییدشده نمایش داده می‌شود.</p></div><div className="rounded-2xl bg-red-500/10 px-3 py-2 text-center"><b className="block text-lg text-red-200">{liveCount}</b><span className="text-[8px] text-slate-500">بازی زنده</span></div></div></section> : <div className="grid grid-cols-3 gap-2">{[-1,0,1].map((n) => <button key={n} onClick={() => setDay(n)} className={`rounded-2xl p-3 text-center ${day === n ? "bg-emerald-400 text-slate-950" : "glass"}`}><CalendarDays size={16} className="mx-auto mb-1"/><b className="text-xs">{n === -1 ? "دیروز" : n === 1 ? "فردا" : "امروز"}</b><div className="text-[9px] opacity-70">{new Date(iranDate(n)).toLocaleDateString("fa-IR", { day: "numeric", month: "long", timeZone: "Asia/Tehran" })}</div></button>)}</div>}
    <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-emerald-400 text-slate-950 p-3 text-center"><Radio size={16} className="mx-auto mb-1"/><b className="text-sm">زنده</b><div className="text-[10px]">{liveCount} بازی</div></div><div className="glass rounded-2xl p-3 text-center"><Clock3 size={16} className="mx-auto mb-1 text-slate-400"/><b className="text-sm">{liveOnly ? "لحظه‌ای" : dayLabel}</b><div className="text-[10px] text-slate-500">{games.length} بازی</div></div><div className="glass rounded-2xl p-3 text-center"><Trophy size={16} className="mx-auto mb-1 text-slate-400"/><b className="text-sm">لیگ‌ها</b><div className="text-[10px] text-slate-500">{Object.keys(grouped).length}</div></div></div>
    {error && <div className="rounded-2xl border border-amber-400/15 bg-amber-400/5 px-4 py-3 text-[11px] text-amber-200">اتصال داده زنده برقرار نشد: {error}</div>}
    {loading ? <section className="glass card p-8 text-center text-sm text-slate-400">{liveOnly ? "در حال دریافت بازی‌های زنده واقعی…" : "در حال دریافت مسابقات واقعی…"}</section> : Object.keys(grouped).length ? <section className="space-y-4">{Object.entries(grouped).map(([league, list]) => <div key={league}><div className="px-1 mb-2 text-xs font-black text-slate-400">{league}</div><div className="space-y-3">{list.map(g => <Link key={g.id} href={g.detailAvailable === false ? `/matches?date=${date}` : `/matches/${g.id}`} className={`glass card block overflow-hidden active:scale-[.99] transition ${settings.compactScores ? "p-3" : "p-4"}`}><div className="flex justify-between items-center mb-4"><span className="text-[11px] text-slate-400">{g.league}</span>{g.live?<span className="flex items-center gap-1 text-[10px] text-emerald-400 font-black"><i className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse"/> LIVE · {g.minute}</span>:<span className="text-[10px] text-slate-500">{g.minute}</span>}</div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="text-center"><div className="mx-auto h-11 w-11 rounded-2xl bg-white/5 grid place-items-center overflow-hidden">{g.homeLogo ? <img src={g.homeLogo} alt="" className="h-8 w-8 object-contain"/> : <span className="font-black">{g.home[0]}</span>}</div><div className="mt-2 font-bold text-sm">{g.home}</div></div><div className="text-center"><div className={`text-xl font-black ${g.live ? "text-white" : "text-slate-300"}`}>{g.homeScore != null ? `${g.homeScore} - ${g.awayScore}` : "—"}</div>{g.live && <div className="text-[10px] text-emerald-400 mt-1">در حال بازی</div>}</div><div className="text-center"><div className="mx-auto h-11 w-11 rounded-2xl bg-white/5 grid place-items-center overflow-hidden">{g.awayLogo ? <img src={g.awayLogo} alt="" className="h-8 w-8 object-contain"/> : <span className="font-black">{g.away[0]}</span>}</div><div className="mt-2 font-bold text-sm">{g.away}</div></div></div><div className="mt-4 pt-3 border-t border-white/5 flex justify-between items-center text-[10px] text-slate-500"><span>{g.detailAvailable === false ? "اطلاعات خلاصه مسابقه" : g.live ? "گزارش زنده و آمار مسابقه" : "مرکز مسابقه"}</span><Star size={14}/></div></Link>)}</div></div>)}</section> : <div className="glass rounded-2xl p-8 text-center text-sm text-slate-500">{liveOnly ? "در حال حاضر مسابقه زنده‌ای پیدا نشد." : "برای این روز مسابقه‌ای پیدا نشد."}</div>}
  </div></main>;
}