"use client";

import { ArrowRight, Bell, CalendarDays, ChevronLeft, Clock3, Radio, Star, Trophy } from "lucide-react";

const games = [
  { league: "لیگ قهرمانان اروپا", home: "بارسلونا", away: "پاری‌سن‌ژرمن", score: "2 - 1", minute: "74'", live: true, events: ["⚽ 18'", "🟨 41'", "⚽ 63'"] },
  { league: "پریمیر لیگ", home: "آرسنال", away: "لیورپول", score: "1 - 1", minute: "نیمه دوم", live: true, events: ["⚽ 22'", "⚽ 51'"] },
  { league: "لالیگا", home: "رئال مادرید", away: "اتلتیکو مادرید", score: "21:00", minute: "امشب", live: false, events: [] },
];

export default function MatchesPage() {
  return <main className="fot-shell"><div className="fot-container space-y-5">
    <header className="flex items-center justify-between"><div className="flex items-center gap-3"><button className="glass h-10 w-10 rounded-xl grid place-items-center"><ArrowRight size={19}/></button><div><h1 className="text-xl font-black">مرکز بازی‌ها</h1><p className="text-[11px] text-slate-500">نتایج و مسابقات امروز</p></div></div><button className="glass h-10 w-10 rounded-xl grid place-items-center"><Bell size={18}/></button></header>
    <div className="glass rounded-2xl p-2 flex items-center gap-2"><CalendarDays size={18} className="mr-2 text-emerald-400"/><div className="flex-1"><div className="text-xs text-slate-400">امروز</div><div className="font-bold text-sm">شنبه، ۱۷ شهریور</div></div><ChevronLeft size={18} className="text-slate-500"/></div>
    <div className="grid grid-cols-3 gap-2"><div className="rounded-2xl bg-emerald-400 text-slate-950 p-3 text-center"><Radio size={16} className="mx-auto mb-1"/><b className="text-sm">زنده</b><div className="text-[10px]">۲ بازی</div></div><div className="glass rounded-2xl p-3 text-center"><Clock3 size={16} className="mx-auto mb-1 text-slate-400"/><b className="text-sm">امروز</b><div className="text-[10px] text-slate-500">۱۲ بازی</div></div><div className="glass rounded-2xl p-3 text-center"><Trophy size={16} className="mx-auto mb-1 text-slate-400"/><b className="text-sm">همه</b><div className="text-[10px] text-slate-500">۳۶ بازی</div></div></div>
    <section className="space-y-3">{games.map(g=><article key={g.home} className="glass card p-4 overflow-hidden"><div className="flex justify-between items-center mb-4"><span className="text-[11px] text-slate-400">{g.league}</span>{g.live?<span className="flex items-center gap-1 text-[10px] text-emerald-400 font-black"><i className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse"/> LIVE</span>:<span className="text-[10px] text-slate-500">{g.minute}</span>}</div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="text-center"><div className="mx-auto h-11 w-11 rounded-2xl bg-blue-500/15 text-blue-300 grid place-items-center font-black">{g.home[0]}</div><div className="mt-2 font-bold text-sm">{g.home}</div></div><div className="text-center"><div className={`text-xl font-black ${g.live?'text-white':'text-slate-300'}`}>{g.score}</div>{g.live&&<div className="text-[10px] text-emerald-400 mt-1">{g.minute}</div>}</div><div className="text-center"><div className="mx-auto h-11 w-11 rounded-2xl bg-red-500/15 text-red-300 grid place-items-center font-black">{g.away[0]}</div><div className="mt-2 font-bold text-sm">{g.away}</div></div></div>{g.events.length>0&&<div className="mt-4 flex gap-2 overflow-x-auto scrollbar-none">{g.events.map(e=><span key={e} className="shrink-0 rounded-full bg-white/[.04] px-3 py-1.5 text-[10px] text-slate-400">{e}</span>)}</div>}<div className="mt-4 pt-3 border-t border-white/5 flex justify-between items-center text-[10px] text-slate-500"><span>مشاهده مرکز مسابقه</span><Star size={14}/></div></article>)}</section>
  </div></main>;
}
