"use client";

import Link from "next/link";
import { ArrowRight, ChevronLeft, Crown, Flag, Search, Trophy } from "lucide-react";
import { useMemo, useState } from "react";
import { CLUB_CUPS, CONTINENTS, LEAGUE_ENTRIES } from "../../lib/fot10-universe";

export default function LeaguesPage() {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); if (!value) return LEAGUE_ENTRIES; return LEAGUE_ENTRIES.filter((item) => `${item.name} ${item.apiCountry} ${item.leagueName}`.toLowerCase().includes(value)); }, [query]);
  return <main className="fot-shell"><div className="fot-container space-y-5">
    <header className="flex items-center gap-3"><Link href="/" aria-label="بازگشت" className="glass h-10 w-10 rounded-xl grid place-items-center"><ArrowRight size={19}/></Link><div><h1 className="text-xl font-black">لیگ‌ها و رقابت‌ها</h1><p className="text-[11px] text-slate-500">۶ قاره · هر قاره ۱۰ کشور · فوتبال باشگاهی و ملی</p></div></header>
    <Link href="/national-teams" className="glass rounded-2xl p-4 flex items-center gap-3 active:scale-[.99] transition-transform"><span className="h-11 w-11 rounded-2xl bg-emerald-400/10 grid place-items-center"><Flag className="text-emerald-400" size={20}/></span><span className="flex-1"><b className="block text-sm">مرکز تیم‌های ملی پنج قاره</b><small className="text-[10px] text-slate-500">بازی‌های ملی، نتایج، فهرست بازیکنان و تیم‌های محبوب</small></span><ChevronLeft size={16} className="text-slate-600"/></Link>
    <Link href="/leagues/ucl" className="glass card p-5 relative overflow-hidden block active:scale-[.99] transition-transform"><Crown className="absolute left-4 top-4 text-yellow-400/50"/><p className="text-xs text-slate-400">جام‌های باشگاهی منتخب</p><h2 className="text-2xl font-black mt-1">اروپا · آسیا · آفریقا · آمریکا</h2><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl bg-white/[.04] p-3"><b>{CLUB_CUPS.length}</b><p className="text-[9px] text-slate-500 mt-1">جام قاره‌ای</p></div><div className="rounded-xl bg-white/[.04] p-3"><b>۶۰</b><p className="text-[9px] text-slate-500 mt-1">کشور</p></div><div className="rounded-xl bg-white/[.04] p-3"><b>۱۰</b><p className="text-[9px] text-slate-500 mt-1">کشور در هر قاره</p></div></div></Link>
    <div className="relative"><Search className="absolute right-4 top-3.5 text-slate-500" size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} className="glass w-full rounded-2xl py-3 pr-11 pl-4 outline-none" placeholder="جستجوی لیگ یا کشور..."/></div>
    <section className="space-y-5">{CONTINENTS.map((continent) => { const items = filtered.filter((item) => item.continent === continent.slug); if (!items.length) return null; return <div key={continent.slug} className="space-y-2"><div className="flex items-center justify-between px-1"><h2 className="font-black text-sm">{continent.icon} {continent.name}</h2><span className="text-[10px] text-slate-500">{items.length} کشور</span></div><div className="grid grid-cols-1 gap-2">{items.map((league) => <Link key={league.slug} href={`/leagues/${league.slug}`} className="glass rounded-2xl p-4 flex items-center gap-3 text-right active:scale-[.99] transition-transform"><span className="h-11 w-11 rounded-2xl bg-white/[.04] grid place-items-center text-xl">{league.flag}</span><span className="flex-1"><b className="block text-sm">{league.leagueName}</b><small className="text-[10px] text-slate-500">{league.name} · جدول · نتایج · برنامه</small></span><Trophy size={16} className="text-slate-600"/><ChevronLeft size={16} className="text-slate-600"/></Link>)}</div></div>})}</section>
    <section className="space-y-2"><h2 className="text-sm font-black">🏆 جام‌های باشگاهی قاره‌ای</h2>{CLUB_CUPS.map((cup) => <Link key={cup.slug} href={`/leagues/${cup.slug}`} className="glass rounded-2xl p-4 flex items-center gap-3"><span className="text-2xl">{cup.icon}</span><span className="flex-1"><b className="block text-sm">{cup.name}</b><small className="text-[10px] text-slate-500">{cup.country}</small></span><ChevronLeft size={16} className="text-slate-600"/></Link>)}</section>
  </div></main>;
}
