import Link from "next/link";
import { ArrowRight, BarChart3, CalendarDays, Goal, Hand, ListOrdered, Newspaper, Trophy, Users, Activity } from "lucide-react";
import { CLUB_CUPS, LEAGUE_ENTRIES } from "../../../lib/fot10-universe";
import { getLeagueByCountry, getLeagueCurrentSeason, getTopScorers, getTopAssists } from "../../../lib/sports-data";
import { getMatchesResilient, getStandingsResilient, getPlayerStatsResilient } from "../../../lib/football-resilient";
import FavoriteButton from "../../../components/FavoriteButton";

const TABS = [["overview", "در یک نگاه", BarChart3], ["table", "جدول", ListOrdered], ["matches", "بازی‌ها", CalendarDays], ["stats", "آمار", Goal], ["news", "اخبار", Newspaper]];
const FINISHED = ["FT", "AET", "PEN"];
const todayTehran = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran" }).format(new Date());
const faDate = d => new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", weekday: "short", day: "numeric", month: "long" }).format(new Date(d));
const faTime = d => new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit" }).format(new Date(d));
const norm = n => String(n || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().replace(/\b(fc|sc|club|sazi)\b/g, "").replace(/\s+/g, " ").trim();
const leagueLogo = id => id ? `https://media.api-sports.io/football/leagues/${id}.png` : null;
const teamLogo = id => id ? `https://media.api-sports.io/football/teams/${id}.png` : null;
function resultForTeam(m, team) { const t = norm(team), h = norm(m.home), a = norm(m.away); if (t !== h && t !== a) return null; const hs = Number(m.homeScore), as = Number(m.awayScore); if (!Number.isFinite(hs) || !Number.isFinite(as)) return null; return hs === as ? "D" : (t === h ? hs > as : as > hs) ? "W" : "L"; }

export default async function League360Page({ params, searchParams }) {
  const entry = LEAGUE_ENTRIES.find(x => x.slug === params.slug);
  const cup = CLUB_CUPS.find(x => x.slug === params.slug);
  if (!entry && !cup) return <main className="fot-shell"><div className="fot-container py-20 text-center"><h1 className="text-xl font-black">رقابت پیدا نشد</h1><Link href="/leagues" className="text-cyan-400 text-sm mt-4 inline-block">بازگشت به رقابت‌ها</Link></div></main>;
  const league = entry || { name: cup.name, leagueName: cup.name, apiCountry: cup.country, flag: cup.icon, leagueId: cup.id };
  const tab = TABS.some(([id]) => id === searchParams?.tab) ? searchParams.tab : "overview";
  let today = [], seasonMatches = [], standings = [], scorers = [], assists = [], season = null, resolved = null, warning = null;
  try {
    resolved = league.leagueId ? { league: { id: league.leagueId, name: league.leagueName } } : await getLeagueByCountry(league.apiCountry, league.leagueName);
    const id = resolved?.league?.id;
    if (!id) throw new Error("league unavailable");
    season = Number(id) === 195 ? 2026 : await getLeagueCurrentSeason(id);
    const rs = await Promise.allSettled([
      getMatchesResilient({ date: todayTehran(), league: id, season }),
      getMatchesResilient({ league: id, season }),
      getStandingsResilient(id, season),
      getPlayerStatsResilient("scorers", id, season, getTopScorers),
      getPlayerStatsResilient("assists", id, season, getTopAssists),
    ]);
    if (rs[0].status === "fulfilled") today = rs[0].value.data || [];
    if (rs[1].status === "fulfilled") seasonMatches = rs[1].value.data || [];
    if (rs[2].status === "fulfilled") standings = rs[2].value.data || [];
    if (rs[3].status === "fulfilled") scorers = rs[3].value.data || [];
    if (rs[4].status === "fulfilled") assists = rs[4].value.data || [];
    if (rs.some(r => r.status === "fulfilled" && r.value?.fallback)) warning = "بخشی از داده‌ها با سرویس جایگزین مطمئن نمایش داده شد.";
  } catch (e) { warning = e instanceof Error ? e.message : "دریافت اطلاعات رقابت ناموفق بود."; }

  const leagueId = resolved?.league?.id || league.leagueId || null;
  const rows = standings.flatMap(x => x?.league?.standings || []).flat();
  const finished = seasonMatches.filter(m => FINISHED.includes(m.statusShort)).sort((a,b) => new Date(b.date) - new Date(a.date));
  const upcoming = seasonMatches.filter(m => m?.date && new Date(m.date) > new Date() && !FINISHED.includes(m.statusShort)).sort((a,b) => new Date(a.date) - new Date(b.date)).slice(0, 12);
  const logoMap = new Map();
  seasonMatches.forEach(m => { if (m?.home && m?.homeLogo) logoMap.set(norm(m.home), m.homeLogo); if (m?.away && m?.awayLogo) logoMap.set(norm(m.away), m.awayLogo); });
  const getLogo = (name,id) => logoMap.get(norm(name)) || teamLogo(id);
  const teamHref = r => r?.team?.id && !String(r.team.id).startsWith("iran-") ? `/teams/${r.team.id}` : `/teams?search=${encodeURIComponent(r?.team?.name || "")}`;
  const form = r => finished.filter(m => resultForTeam(m, r?.team?.name)).slice(0,5).map(m => resultForTeam(m, r?.team?.name));
  const totalGoals = rows.reduce((s,r) => s + Number(r?.all?.goals?.for || 0), 0);
  const totalMatches = finished.length;
  const bestAttack = [...rows].filter(r => Number.isFinite(Number(r?.all?.goals?.for))).sort((a,b) => b.all.goals.for-a.all.goals.for)[0];
  const bestDefense = [...rows].filter(r => Number.isFinite(Number(r?.all?.goals?.against))).sort((a,b) => a.all.goals.against-b.all.goals.against)[0];
  const bestWins = [...rows].filter(r => Number.isFinite(Number(r?.all?.win))).sort((a,b) => b.all.win-a.all.win)[0];

  const Table = () => <section className="glass rounded-[28px] border border-white/10 overflow-hidden"><div className="p-4 sm:p-5 border-b border-white/10 flex justify-between items-center"><div><p className="text-[9px] tracking-[.18em] text-cyan-300 font-black">COMPETITION TABLE</p><h2 className="text-lg sm:text-xl font-black mt-1 flex items-center gap-2"><Trophy size={18}/> جدول رده‌بندی</h2></div><span className="text-[9px] text-slate-500">فصل {season || "—"}</span></div><div className="overflow-x-auto"><div className="min-w-[730px] text-[9px] sm:text-[10px]"><div className="grid grid-cols-[2.5rem_minmax(190px,1fr)_3rem_3rem_3rem_3rem_3.5rem_3.5rem_3.5rem_4rem] bg-white/[.035] text-slate-500 font-bold">{["#","تیم","بازی","برد","مساوی","باخت","گل","تفاضل","فرم","امتیاز"].map(h=><span key={h} className="p-3 text-center">{h}</span>)}</div>{rows.map((r,i)=>{const name=r?.team?.name||"—";const logo=getLogo(name,r?.team?.id);return <Link href={teamHref(r)} key={`${name}-${i}`} className="grid grid-cols-[2.5rem_minmax(190px,1fr)_3rem_3rem_3rem_3rem_3.5rem_3.5rem_3.5rem_4rem] border-t border-white/[.06] hover:bg-cyan-400/[.04] transition"><span className="p-3 text-center text-slate-500">{i+1}</span><span className="p-3 flex items-center gap-2 min-w-0 font-bold"><span className="h-7 w-7 rounded-lg bg-white/[.05] border border-white/10 grid place-items-center overflow-hidden shrink-0">{logo?<img src={logo} alt="" className="h-6 w-6 object-contain"/>:"⚽"}</span><span className="truncate">{name}</span></span><span className="p-3 text-center">{r?.all?.played??0}</span><span className="p-3 text-center">{r?.all?.win??0}</span><span className="p-3 text-center">{r?.all?.draw??0}</span><span className="p-3 text-center">{r?.all?.lose??r?.all?.loss??0}</span><span className="p-3 text-center">{r?.all?.goals?.for??0}</span><span className="p-3 text-center">{r?.goalsDiff>0?`+${r.goalsDiff}`:r?.goalsDiff??0}</span><span className="p-2 flex justify-center gap-0.5">{form(r).map((v,j)=><i key={j} className={`not-italic h-5 w-5 rounded-full grid place-items-center text-[8px] font-black ${v==="W"?"bg-emerald-400/20 text-emerald-300":v==="D"?"bg-amber-400/20 text-amber-300":"bg-rose-400/20 text-rose-300"}`}>{v}</i>)}</span><span className="p-3 text-center font-black text-cyan-200">{r?.points??0}</span></Link>})}{!rows.length&&<div className="p-10 text-center text-slate-500">جدول این رقابت در دسترس نیست.</div>}</div></div></section>;

  const Stats = () => <section className="glass rounded-[28px] border border-white/10 overflow-hidden"><div className="p-4 sm:p-5 border-b border-white/10"><p className="text-[9px] tracking-[.18em] text-cyan-300 font-black">LEAGUE STATS</p><h2 className="text-lg sm:text-xl font-black mt-1 flex items-center gap-2"><BarChart3 size={18}/> آمار لیگ</h2><p className="text-[10px] text-slate-500 mt-1">آمار فصل جاری؛ داده‌ای که موجود نباشد نمایش داده نمی‌شود.</p></div><div className="p-4 grid grid-cols-2 lg:grid-cols-4 gap-3">{[["تیم‌ها",rows.length,Users],["بازی‌های انجام‌شده",totalMatches,CalendarDays],["مجموع گل‌ها",totalGoals,Goal],["میانگین گل",totalMatches?(totalGoals/totalMatches).toFixed(2):"—",Activity]].map(([l,v,I])=><div key={l} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-4"><I size={17} className="text-cyan-300"/><span className="block text-[9px] text-slate-500 mt-3">{l}</span><b className="block text-xl mt-1">{v||"—"}</b></div>)}</div><div className="px-4 pb-4 grid sm:grid-cols-3 gap-3">{[[bestAttack,"بهترین خط حمله",bestAttack?.all?.goals?.for,"گل"],[bestDefense,"بهترین خط دفاع",bestDefense?.all?.goals?.against,"گل خورده"],[bestWins,"بیشترین برد",bestWins?.all?.win,"برد"]].filter(x=>x[0]).map(([r,l,v,s])=><div key={l} className="rounded-2xl bg-slate-950/45 border border-white/[.06] p-4"><span className="text-[9px] text-slate-500">{l}</span><strong className="block text-sm mt-2">{r.team?.name}</strong><span className="text-[10px] text-cyan-300 mt-1 block">{v} {s}</span></div>)}</div><div className="border-t border-white/10 p-4 grid lg:grid-cols-2 gap-5"><div><h3 className="font-black text-sm mb-3 flex gap-2 items-center"><Goal size={16}/> برترین گلزنان</h3>{scorers.slice(0,5).map((x,i)=><div key={x?.player?.id||i} className="flex justify-between py-2 border-b border-white/[.05] text-xs"><span><b className="text-slate-500 ml-2">{i+1}</b>{x?.player?.name||"—"}</span><strong>{x?.statistics?.[0]?.goals?.total??x?.goals??"—"}</strong></div>)}</div><div><h3 className="font-black text-sm mb-3 flex gap-2 items-center"><Hand size={16}/> برترین پاسورها</h3>{assists.slice(0,5).map((x,i)=><div key={x?.player?.id||i} className="flex justify-between py-2 border-b border-white/[.05] text-xs"><span><b className="text-slate-500 ml-2">{i+1}</b>{x?.player?.name||"—"}</span><strong>{x?.statistics?.[0]?.goals?.assists??x?.assists??"—"}</strong></div>)}</div></div></section>;

  const Matches = () => <section className="glass rounded-[28px] border border-white/10 p-4 sm:p-5"><div className="flex justify-between mb-4"><div><p className="text-[9px] tracking-[.18em] text-cyan-300 font-black">FIXTURES</p><h2 className="text-lg font-black mt-1">بازی‌های لیگ</h2></div><span className="text-[9px] text-slate-500">{seasonMatches.length} مسابقه</span></div><div className="space-y-2">{[...today,...upcoming].slice(0,16).map((m,i)=><Link href={m?.id?`/matches/${m.id}`:"#"} key={`${m?.id||"m"}-${i}`} className="flex items-center gap-3 rounded-2xl bg-white/[.025] border border-white/[.05] p-3 hover:bg-white/[.05]"><div className="w-20 shrink-0 text-center"><b className="block text-xs">{faTime(m.date)}</b><span className="text-[8px] text-slate-500">{faDate(m.date)}</span></div><div className="flex-1 grid grid-cols-3 items-center text-xs"><span className="text-left font-bold truncate">{m.home}</span><b className="text-center">{m.statusShort==="NS"?"-":`${m.homeScore??"-"} : ${m.awayScore??"-"}`}</b><span className="text-right font-bold truncate">{m.away}</span></div></Link>)}{!seasonMatches.length&&<p className="text-center text-slate-500 text-xs py-8">مسابقه‌ای در دسترس نیست.</p>}</div></section>;

  return <main className="fot-shell min-h-screen pb-12"><div className="fot-container space-y-4 sm:space-y-5"><header className="flex items-center gap-3 pt-1"><Link href="/leagues" className="glass h-10 w-10 rounded-xl grid place-items-center"><ArrowRight size={19}/></Link><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"/><span className="text-[9px] text-emerald-300 font-bold">رقابت فعال</span></div><div className="flex items-center gap-2 mt-1"><span className="h-8 w-8 rounded-lg bg-white/[.06] border border-white/10 grid place-items-center overflow-hidden">{leagueLogo(leagueId)?<img src={leagueLogo(leagueId)} alt="" className="h-7 w-7 object-contain"/>:<span>{league.flag||"🏆"}</span>}</span><h1 className="text-lg sm:text-xl font-black truncate">{league.leagueName}</h1></div><p className="text-[9px] text-slate-500 mt-1">{entry?entry.name:league.apiCountry} · فصل {season||"—"}</p></div><FavoriteButton type="league" name={league.leagueName||""}/></header><section className="relative overflow-hidden rounded-[30px] border border-cyan-300/10 bg-gradient-to-br from-cyan-400/[.15] via-slate-900/95 to-slate-950 p-5 sm:p-7"><div className="relative flex items-center gap-5"><div className="h-20 w-20 sm:h-24 sm:w-24 rounded-3xl bg-white/[.08] border border-white/10 grid place-items-center overflow-hidden shrink-0">{leagueLogo(leagueId)?<img src={leagueLogo(leagueId)} alt="" className="h-14 w-14 object-contain"/>:<span className="text-5xl">{league.flag||"🏆"}</span>}</div><div><span className="text-[8px] text-cyan-200 rounded-full bg-cyan-400/10 border border-cyan-300/20 px-2.5 py-1">FOT10 COMPETITION</span><h2 className="text-2xl sm:text-3xl font-black mt-3">{league.leagueName}</h2><p className="text-[10px] text-slate-400 mt-2">جدول · بازی‌ها · آمار فصل</p></div></div></section><nav className="glass rounded-2xl p-1 grid grid-cols-5 gap-1 sticky top-2 z-20 backdrop-blur-xl border border-white/10">{TABS.map(([id,label,I])=><Link key={id} href={`/leagues/${params.slug}?tab=${id}`} className={`rounded-xl py-2.5 text-[8px] sm:text-[10px] font-bold text-center flex flex-col items-center gap-1 ${tab===id?"bg-cyan-400 text-slate-950 shadow-lg":"text-slate-400 hover:bg-white/5"}`}><I size={15}/>{label}</Link>)}</nav>{warning&&<div className="rounded-2xl border border-amber-300/10 bg-amber-400/[.04] p-3 text-center text-[9px] text-amber-300">{warning}</div>}{tab==="overview"&&<><Table/><Stats/><Matches/></>}{tab==="table"&&<Table/>}{tab==="stats"&&<Stats/>}{tab==="matches"&&<Matches/>}{tab==="news"&&<section className="glass rounded-[28px] p-8 text-center"><Newspaper className="mx-auto text-cyan-300" size={28}/><h2 className="font-black mt-3">اخبار این رقابت</h2><p className="text-xs text-slate-500 mt-2">مرکز اخبار رقابت در حال تکمیل است.</p></section>}</div></main>;
}
