import Link from "next/link";
import { ArrowRight, CalendarDays, Trophy, Goal, Hand, BarChart3, ListOrdered, ChevronLeft, TrendingUp, Clock3, Shield, Zap, Newspaper, Activity, Users, ExternalLink } from "lucide-react";
import { CLUB_CUPS, LEAGUE_ENTRIES } from "../../../lib/fot10-universe";
import { getLeagueByCountry, getLeagueCurrentSeason, getTopScorers, getTopAssists } from "../../../lib/sports-data";
import { getMatchesResilient, getStandingsResilient, getPlayerStatsResilient } from "../../../lib/football-resilient";
import FavoriteButton from "../../../components/FavoriteButton";

export const dynamic = "force-dynamic";

const tabs = [["overview", "خلاصه", BarChart3], ["matches", "بازی‌ها", CalendarDays], ["table", "جدول", ListOrdered], ["stats", "آمار", Goal], ["news", "اخبار", Newspaper]];
const finishedStatuses = ["FT", "AET", "PEN"];
function tehranToday() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran" }).format(new Date()); }
function formatDate(date) { return new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", weekday: "short", day: "numeric", month: "long" }).format(new Date(date)); }
function formatTime(date) { return new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit" }).format(new Date(date)); }
function formatChecked() { return new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", weekday: "long", day: "numeric", month: "long", hour: "2-digit", minute: "2-digit" }).format(new Date()); }
function normalizeTeamName(name) { return String(name || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim().replace(/\b(fc|sc|club|sazi)\b/g, "").replace(/\s+/g, " ").trim(); }
function resultForTeam(match, team) { const t = normalizeTeamName(team), home = normalizeTeamName(match.home), away = normalizeTeamName(match.away); if (t !== home && t !== away) return null; const hs = Number(match.homeScore), as = Number(match.awayScore); if (!Number.isFinite(hs) || !Number.isFinite(as)) return null; if (hs === as) return "D"; return (t === home ? hs > as : as > hs) ? "W" : "L"; }
function errorInfo(result) { if (result?.status !== "rejected") return null; const e = result.reason; return { code: e?.code || "API_ERROR", message: e?.message || "درخواست ناموفق بود." }; }

export default async function LeagueDetailPage({ params, searchParams }) {
  const countryLeague = LEAGUE_ENTRIES.find(x => x.slug === params.slug);
  const cup = CLUB_CUPS.find(x => x.slug === params.slug);
  if (!countryLeague && !cup) return <main className="fot-shell"><div className="fot-container py-20 text-center"><h1 className="text-xl font-black">رقابت پیدا نشد</h1><Link href="/leagues" className="text-sm text-cyan-400 mt-4 inline-block">بازگشت به رقابت‌ها</Link></div></main>;
  const league = countryLeague || { name: cup.name, leagueName: cup.name, apiCountry: cup.country, flag: cup.icon, leagueId: cup.id };
  const today = tehranToday();
  const activeTab = tabs.some(([id]) => id === searchParams?.tab) ? searchParams.tab : "overview";
  const tableMode = searchParams?.table === "summary" ? "summary" : "full";
  let matches = [], seasonMatches = [], standings = [], scorers = [], assists = [], season = null, liveError = null, resolved = null, diagnostics = [];
  try {
    resolved = league.leagueId ? { league: { id: league.leagueId, name: league.leagueName }, source: "configured" } : await getLeagueByCountry(league.apiCountry, league.leagueName);
    const leagueId = resolved?.league?.id;
    if (!leagueId) throw new Error("league unavailable");
    season = Number(leagueId) === 195 ? 2026 : await getLeagueCurrentSeason(leagueId);
    const results = await Promise.allSettled([getMatchesResilient({ date: today, league: leagueId, season }), getMatchesResilient({ league: leagueId, season }), getStandingsResilient(leagueId, season), getPlayerStatsResilient("scorers", leagueId, season, getTopScorers), getPlayerStatsResilient("assists", leagueId, season, getTopAssists)]);
    if (results[0].status === "fulfilled") matches = results[0].value.data || [];
    if (results[1].status === "fulfilled") seasonMatches = results[1].value.data || [];
    if (results[2].status === "fulfilled") standings = results[2].value.data || [];
    if (results[3].status === "fulfilled") scorers = results[3].value.data || [];
    if (results[4].status === "fulfilled") assists = results[4].value.data || [];
    diagnostics = results.map((r, i) => { const names = ["بازی‌های امروز", "بازی‌های فصل", "جدول", "گلزنان", "پاس گل"]; return r.status === "fulfilled" ? { name: names[i], ok: true, count: r.value?.data?.length || 0, source: r.value?.source, fallback: r.value?.fallback } : { name: names[i], ok: false, error: errorInfo(r) }; });
    if (diagnostics.some(x => x.fallback)) liveError = "بخشی از داده‌ها با سرویس جایگزین مطمئن نمایش داده شد.";
  } catch (e) { liveError = e instanceof Error ? e.message : "live data unavailable"; }
  const rows = (standings || []).flatMap(x => { const g = x?.league?.standings || []; return g.flat ? g.flat() : g; }).filter(Boolean);
  const finished = seasonMatches.filter(m => finishedStatuses.includes(m.statusShort)).sort((a, b) => new Date(b.date) - new Date(a.date));
  const upcoming = seasonMatches.filter(m => m?.date && new Date(m.date) > new Date() && !finishedStatuses.includes(m.statusShort)).sort((a, b) => new Date(a.date) - new Date(b.date)).slice(0, 8);
  const teamLogoMap = new Map(); for (const m of seasonMatches) { if (m?.home && m?.homeLogo) teamLogoMap.set(normalizeTeamName(m.home), m.homeLogo); if (m?.away && m?.awayLogo) teamLogoMap.set(normalizeTeamName(m.away), m.awayLogo); }
  const getTeamLogo = name => teamLogoMap.get(normalizeTeamName(name)) || null;
  const teamHref = r => r?.team?.id && !String(r.team.id).startsWith("iran-") ? `/teams/${r.team.id}` : `/teams?search=${encodeURIComponent(r?.team?.name || "")}`;
  const playerHref = x => x?.player?.id && !String(x.player.id).startsWith("iran-") ? `/players/${x.player.id}` : null;
  const formRows = rows.map(r => ({ ...r, form: finished.filter(m => resultForTeam(m, r.team?.name)).slice(0, 5).map(m => resultForTeam(m, r.team?.name)) }));
  const bestAttack = rows.filter(r => Number.isFinite(Number(r.all?.goals?.for))).sort((a, b) => (b.all.goals.for || 0) - (a.all.goals.for || 0))[0];
  const bestDefense = rows.filter(r => Number.isFinite(Number(r.all?.goals?.against))).sort((a, b) => (a.all.goals.against || 0) - (b.all.goals.against || 0))[0];
  const mostWins = rows.filter(r => Number.isFinite(Number(r.all?.win))).sort((a, b) => (b.all.win || 0) - (a.all.win || 0))[0];
  const totalGoals = rows.reduce((sum, r) => sum + Number(r.all?.goals?.for || 0), 0);
  const statCards = [["بازی امروز", matches.length, CalendarDays], ["تیم‌ها", rows.length || "—", Users], ["گلزنان", scorers.length || "—", Goal], ["پاسورها", assists.length || "—", Hand]];

  return <main className="fot-shell min-h-screen pb-12"><div className="fot-container space-y-4 sm:space-y-5">
    <header className="flex items-center gap-3 pt-1"><Link href="/leagues" aria-label="بازگشت" className="glass h-10 w-10 rounded-xl grid place-items-center hover:bg-white/10"><ArrowRight size={19}/></Link><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"/><span className="text-[10px] text-emerald-300 font-bold">رقابت فعال</span></div><h1 className="text-lg sm:text-xl font-black truncate">{league.flag} {league.leagueName}</h1><p className="text-[10px] text-slate-500">{countryLeague ? countryLeague.name : league.apiCountry} · فصل {season}</p></div><FavoriteButton type="league" name={league.leagueName || ""} className="shrink-0"/></header>
    <section className="relative overflow-hidden rounded-[28px] border border-cyan-300/10 bg-gradient-to-br from-cyan-400/[.18] via-slate-900/90 to-slate-950 p-5 sm:p-7 shadow-2xl"><div className="absolute -top-20 -left-20 h-48 w-48 rounded-full bg-cyan-400/10 blur-3xl"/><div className="relative flex flex-col lg:flex-row lg:items-center gap-6"><div className="flex items-center gap-4 flex-1"><div className="h-20 w-20 sm:h-24 sm:w-24 rounded-3xl bg-white/[.08] border border-white/10 grid place-items-center text-5xl shrink-0 shadow-xl">{league.flag}</div><div className="min-w-0"><div className="flex flex-wrap gap-2 mb-2"><span className="rounded-full bg-cyan-400/10 border border-cyan-300/20 px-2.5 py-1 text-[9px] text-cyan-200">FOT10 LEAGUE</span><span className="rounded-full bg-white/[.06] px-2.5 py-1 text-[9px] text-slate-400">{season}</span></div><h2 className="text-2xl sm:text-3xl font-black truncate">{league.leagueName}</h2><p className="text-[11px] text-slate-400 mt-2">{countryLeague ? countryLeague.name : league.apiCountry} · مرکز حرفه‌ای رقابت</p><p className="text-[9px] text-slate-500 mt-2">آخرین بررسی FOT10: {formatChecked()}</p></div></div><div className="grid grid-cols-2 sm:grid-cols-4 lg:w-[470px] gap-2">{statCards.map(([label, value, Icon]) => <div key={label} className="rounded-2xl border border-white/5 bg-black/25 p-3.5"><div className="flex justify-between items-center"><span className="text-[9px] text-slate-500">{label}</span><Icon size={14} className="text-cyan-300"/></div><b className="block text-xl mt-2">{value}</b></div>)}</div></div></section>
    <nav className="glass rounded-2xl p-1 grid grid-cols-5 gap-1 sticky top-2 z-20 backdrop-blur-xl border border-white/10">{tabs.map(([id, label, Icon]) => <Link key={id} href={`/leagues/${params.slug}?tab=${id}`} className={`rounded-xl px-1 py-2.5 text-[9px] sm:text-[11px] font-bold text-center flex flex-col items-center gap-1 transition ${activeTab === id ? "bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-400/10" : "text-slate-400 hover:bg-white/5"}`}><Icon size={15}/>{label}</Link>)}</nav>
    {liveError && <div className="glass rounded-2xl p-3 flex items-center justify-center gap-2 text-[10px] text-amber-300"><Activity size={14}/>{liveError}</div>}
    {(activeTab === "overview" || activeTab === "matches") && <section className="grid lg:grid-cols-[1.15fr_.85fr] gap-4"><div className="space-y-2.5"><div className="flex items-end justify-between px-1"><div><p className="text-[9px] text-cyan-300 font-bold tracking-widest">MATCH CENTER</p><h2 className="flex items-center gap-2 text-base font-black mt-1"><CalendarDays size={17}/> بازی‌های امروز</h2></div><span className="rounded-lg bg-white/[.04] px-2 py-1 text-[9px] text-slate-500">{today}</span></div>{matches.length ? matches.slice(0, 10).map(m => <Link key={m.id} href={`/matches/${m.id}`} className="group glass rounded-2xl p-3.5 flex items-center gap-3 hover:bg-white/[.06] border border-white/5"><div className="h-11 w-11 rounded-xl bg-white/[.05] grid place-items-center overflow-hidden">{m.homeLogo ? <img src={m.homeLogo} alt="" className="h-9 w-9 object-contain"/> : "⚽"}</div><div className="flex-1 min-w-0"><b className="block text-xs truncate">{m.home}</b><b className="block text-xs mt-1 truncate">{m.away}</b></div><div className="text-left"><span className="rounded-lg bg-cyan-400/10 text-cyan-200 px-2.5 py-1.5 text-[10px] font-black">{m.statusShort === "NS" ? formatTime(m.date) : `${m.homeScore ?? 0} - ${m.awayScore ?? 0}`}</span><ChevronLeft size={13} className="ml-auto mt-2 text-slate-600 group-hover:text-cyan-300"/></div></Link>) : <div className="glass rounded-2xl p-8 text-center text-xs text-slate-500">امروز بازی ثبت‌شده‌ای پیدا نشد.</div>}</div><div className="space-y-2.5"><div className="px-1"><p className="text-[9px] text-amber-300 font-bold tracking-widest">UPCOMING</p><h2 className="flex items-center gap-2 text-base font-black mt-1"><Clock3 size={17}/> برنامه پیش‌رو</h2></div>{upcoming.length ? upcoming.slice(0, 5).map(m => { const hl = m.homeLogo || getTeamLogo(m.home), al = m.awayLogo || getTeamLogo(m.away); return <Link key={`up-${m.id}`} href={`/matches/${m.id}`} className="group glass rounded-2xl p-3.5 block hover:bg-white/[.06] border border-white/5"><div className="text-[9px] text-amber-300"><CalendarDays size={12} className="inline ml-1"/>{formatDate(m.date)} · {formatTime(m.date)}</div><div className="mt-2 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><div className="flex items-center gap-2 min-w-0"><span className="h-7 w-7 rounded-lg bg-white/[.05] grid place-items-center overflow-hidden shrink-0">{hl ? <img src={hl} alt="" className="h-6 w-6 object-contain"/> : "⚽"}</span><b className="text-[10px] truncate">{m.home}</b></div><span className="text-[9px] text-slate-600">VS</span><div className="flex items-center gap-2 min-w-0 justify-end"><b className="text-[10px] truncate text-left">{m.away}</b><span className="h-7 w-7 rounded-lg bg-white/[.05] grid place-items-center overflow-hidden shrink-0">{al ? <img src={al} alt="" className="h-6 w-6 object-contain"/> : "⚽"}</span></div></div></Link>; }) : <div className="glass rounded-2xl p-8 text-center text-xs text-slate-500">بازی آینده‌ای پیدا نشد.</div>}</div></section>}

    {(activeTab === "overview" || activeTab === "table") && <section className="glass rounded-3xl p-4 sm:p-5"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 mb-4"><div><p className="text-[9px] text-cyan-300 font-bold tracking-widest">STANDINGS</p><h2 className="flex items-center gap-2 text-lg font-black mt-1"><Trophy size={18}/> جدول رسمی FOT10</h2></div><div className="flex gap-1 rounded-xl bg-black/20 p-1 self-start"><Link href={`/leagues/${params.slug}?tab=table&table=full`} className={`px-3 py-1.5 rounded-lg text-[9px] font-bold ${tableMode === "full" ? "bg-cyan-400 text-slate-950" : "text-slate-500"}`}>کامل</Link><Link href={`/leagues/${params.slug}?tab=table&table=summary`} className={`px-3 py-1.5 rounded-lg text-[9px] font-bold ${tableMode === "summary" ? "bg-cyan-400 text-slate-950" : "text-slate-500"}`}>خلاصه</Link></div></div><div className="overflow-x-auto"><div className="min-w-[760px] grid grid-cols-[2.2rem_minmax(150px,1fr)_3.5rem_3.5rem_3.5rem_3.5rem_4rem_4rem_4rem_4rem] text-[9px] sm:text-[10px]"><div className="contents text-slate-500 bg-white/[.04] font-bold"><span className="p-3 text-center">#</span><span className="p-3 text-right">تیم</span><span className="p-3 text-center">بازی</span><span className="p-3 text-center">برد</span><span className="p-3 text-center">مساوی</span><span className="p-3 text-center">باخت</span><span className="p-3 text-center">گل‌زده</span><span className="p-3 text-center">گل‌خورده</span><span className="p-3 text-center">تفاضل</span><span className="p-3 text-center">امتیاز</span></div>{rows.map((r, i) => <div key={`${r?.team?.id || r?.team?.name || i}-${r.rank}`} className="contents"><span className="p-2.5 flex items-center justify-center border-t border-white/5"><span className={`h-7 min-w-7 px-1 rounded-lg grid place-items-center text-[10px] font-black ${r.rank <= 3 ? (r.rank === 1 ? "bg-amber-400 text-slate-950" : r.rank === 2 ? "bg-slate-300 text-slate-950" : "bg-orange-300 text-slate-950") : "bg-white/[.06] text-slate-400"}`}>{r.rank}</span></span><Link href={teamHref(r)} className="p-2.5 flex items-center gap-2 min-w-0 border-t border-white/5 hover:bg-white/[.04]"><span className="h-8 w-8 rounded-lg bg-white/[.06] grid place-items-center overflow-hidden shrink-0">{getTeamLogo(r?.team?.name) ? <img src={getTeamLogo(r?.team?.name)} alt="" className="h-7 w-7 object-contain"/> : "⚽"}</span><span className="font-bold truncate">{r?.team?.name || "—"}</span></Link>{[r.all?.played ?? 0, r.all?.win ?? 0, r.all?.draw ?? 0, r.all?.lose ?? r.all?.loss ?? 0, r.all?.goals?.for ?? 0, r.all?.goals?.against ?? 0, Number(r.goalsDiff) > 0 ? `+${r.goalsDiff}` : (r.goalsDiff ?? 0), r.points ?? 0].map((x,j) => <span key={j} className="p-2.5 flex items-center justify-center border-t border-white/5 font-semibold text-slate-300">{x}</span>)}</div>)}</div></div></section>}

    {(activeTab === "overview" || activeTab === "stats") && <section className="grid lg:grid-cols-2 gap-4"><div className="glass rounded-3xl p-4 sm:p-5"><div className="flex items-end justify-between mb-4"><div><p className="text-[9px] text-amber-300 font-bold tracking-widest">TOP SCORERS</p><h2 className="text-lg font-black mt-1">برترین گلزنان</h2></div><span className="text-[9px] text-slate-600">{scorers.length} نفر</span></div>{scorers.length ? scorers.slice(0, 5).map((x,i) => { const href=playerHref(x); const body=<div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg bg-white/[.06] grid place-items-center text-[10px] font-black">{i+1}</span><div className="h-10 w-10 rounded-xl bg-white/[.05] overflow-hidden grid place-items-center">{x.player?.photo ? <img src={x.player.photo} alt="" className="h-10 w-10 object-cover"/> : "👤"}</div><div className="min-w-0 flex-1"><b className="block text-xs truncate">{x.player?.name || "—"}</b><span className="text-[9px] text-slate-500">{x.team?.name || "—"}</span></div><strong className="text-lg text-cyan-300">{x.goals ?? x.statistics?.[0]?.goals?.total ?? 0}</strong></div>; return href ? <Link key={x.player?.id || i} href={href} className="block py-2.5 border-b border-white/5">{body}</Link> : <div key={i} className="py-2.5 border-b border-white/5">{body}</div>; }) : <div className="text-center py-10 text-xs text-slate-500">آمار گلزنان در دسترس نیست.</div>}</div><div className="glass rounded-3xl p-4 sm:p-5"><div className="flex items-end justify-between mb-4"><div><p className="text-[9px] text-cyan-300 font-bold tracking-widest">TOP ASSISTS</p><h2 className="text-lg font-black mt-1">برترین پاسورها</h2></div><span className="text-[9px] text-slate-600">{assists.length} نفر</span></div>{assists.length ? assists.slice(0, 5).map((x,i) => { const href=playerHref(x); const body=<div className="flex items-center gap-3"><span className="h-8 w-8 rounded-lg bg-white/[.06] grid place-items-center text-[10px] font-black">{i+1}</span><div className="h-10 w-10 rounded-xl bg-white/[.05] overflow-hidden grid place-items-center">{x.player?.photo ? <img src={x.player.photo} alt="" className="h-10 w-10 object-cover"/> : "👤"}</div><div className="min-w-0 flex-1"><b className="block text-xs truncate">{x.player?.name || "—"}</b><span className="text-[9px] text-slate-500">{x.team?.name || "—"}</span></div><strong className="text-lg text-cyan-300">{x.assists ?? x.statistics?.[0]?.goals?.assists ?? 0}</strong></div>; return href ? <Link key={x.player?.id || i} href={href} className="block py-2.5 border-b border-white/5">{body}</Link> : <div key={i} className="py-2.5 border-b border-white/5">{body}</div>; }) : <div className="text-center py-10 text-xs text-slate-500">آمار پاس گل در دسترس نیست.</div>}</div></section>}

    {(activeTab === "overview" || activeTab === "stats") && <section className="grid grid-cols-2 lg:grid-cols-4 gap-2.5"><div className="glass rounded-2xl p-4"><span className="text-[9px] text-slate-500">گل‌های ثبت‌شده</span><b className="block text-2xl mt-1">{totalGoals || "—"}</b></div><div className="glass rounded-2xl p-4"><span className="text-[9px] text-slate-500">بهترین حمله</span><b className="block text-sm mt-1 truncate">{bestAttack?.team?.name || "—"}</b></div><div className="glass rounded-2xl p-4"><span className="text-[9px] text-slate-500">بهترین دفاع</span><b className="block text-sm mt-1 truncate">{bestDefense?.team?.name || "—"}</b></div><div className="glass rounded-2xl p-4"><span className="text-[9px] text-slate-500">بیشترین برد</span><b className="block text-sm mt-1 truncate">{mostWins?.team?.name || "—"}</b></div></section>}

    {(activeTab === "overview" || activeTab === "matches") && <section className="glass rounded-3xl p-4 sm:p-5"><div className="flex items-end justify-between mb-4"><div><p className="text-[9px] text-cyan-300 font-bold tracking-widest">RECENT RESULTS</p><h2 className="text-lg font-black mt-1">آخرین نتایج</h2></div><span className="text-[9px] text-slate-600">{finished.length} بازی</span></div>{finished.length ? finished.slice(0, 8).map(m => <Link key={`res-${m.id}`} href={`/matches/${m.id}`} className="flex items-center gap-2 py-3 border-b border-white/5"><span className="text-[9px] text-slate-600 w-20 shrink-0">{formatDate(m.date)}</span><span className="flex-1 text-[10px] font-semibold text-left truncate">{m.home}</span><b className="text-xs w-16 text-center">{m.homeScore ?? 0} - {m.awayScore ?? 0}</b><span className="flex-1 text-[10px] font-semibold truncate">{m.away}</span></Link>) : <div className="text-center py-10 text-xs text-slate-500">نتیجه‌ای ثبت نشده است.</div>}</section>}
    {(activeTab === "overview" || activeTab === "news") && <section className="glass rounded-3xl p-5 text-center"><Newspaper size={24} className="mx-auto text-cyan-300"/><h2 className="text-lg font-black mt-2">اخبار رقابت</h2><p className="text-xs text-slate-500 mt-2">این بخش آماده اتصال به فید خبری رسمی است.</p></section>}
    {activeTab === "overview" && <section className="grid lg:grid-cols-2 gap-4"><div className="glass rounded-3xl p-5"><div className="flex items-center gap-2"><TrendingUp size={18} className="text-cyan-300"/><h2 className="font-black">فرم اخیر تیم‌ها</h2></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-4">{formRows.slice(0, 8).map(r => <Link key={`form-${r.rank}`} href={teamHref(r)} className="rounded-2xl bg-white/[.03] border border-white/5 p-3 flex items-center gap-3"><span className={`h-8 w-8 rounded-lg grid place-items-center font-black text-[10px] ${rankClass(r.rank)}`}>{r.rank}</span><div className="min-w-0 flex-1"><b className="text-[10px] truncate block">{r.team?.name}</b><div className="flex gap-1 mt-1">{r.form.length ? r.form.map((f,j) => <span key={j} className={`h-5 w-5 rounded-full grid place-items-center text-[8px] font-black ${f === "W" ? "bg-emerald-400/20 text-emerald-300" : f === "D" ? "bg-amber-400/20 text-amber-300" : "bg-rose-400/20 text-rose-300"}`}>{f}</span>) : <span className="text-[8px] text-slate-600">بدون داده</span>}</div></div></Link>)}</div></div><div className="glass rounded-3xl p-5"><div className="flex items-center gap-2"><Shield size={18} className="text-cyan-300"/><h2 className="font-black">نکات سریع</h2></div><div className="space-y-2 mt-4 text-[10px] text-slate-400"><div className="rounded-xl bg-white/[.03] p-3">برد بیشتر: <b className="text-slate-200">{mostWins?.team?.name || "—"}</b></div><div className="rounded-xl bg-white/[.03] p-3">بهترین خط حمله: <b className="text-slate-200">{bestAttack?.team?.name || "—"}</b></div><div className="rounded-xl bg-white/[.03] p-3">بهترین خط دفاع: <b className="text-slate-200">{bestDefense?.team?.name || "—"}</b></div></div></div></section>}
  </div></main>;
}
