import Link from "next/link";
import { ArrowRight, CalendarDays, Trophy, Goal, Hand, BarChart3, ListOrdered, ChevronLeft, TrendingUp, Clock3, Shield, Zap, Newspaper, Activity } from "lucide-react";
import { CLUB_CUPS, LEAGUE_ENTRIES } from "../../../lib/fot10-universe";
import { getLeagueByCountry, getLeagueCurrentSeason, getTopScorers, getTopAssists } from "../../../lib/sports-data";
import { getMatchesResilient, getStandingsResilient, getPlayerStatsResilient } from "../../../lib/football-resilient";
import FavoriteButton from "../../../components/FavoriteButton";

export const dynamic = "force-dynamic";

function tehranToday(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran"}).format(new Date())}
function formatDate(date){return new Intl.DateTimeFormat("fa-IR",{timeZone:"Asia/Tehran",weekday:"short",day:"numeric",month:"long"}).format(new Date(date))}
function formatTime(date){return new Intl.DateTimeFormat("fa-IR",{timeZone:"Asia/Tehran",hour:"2-digit",minute:"2-digit"}).format(new Date(date))}
function formatChecked(){return new Intl.DateTimeFormat("fa-IR",{timeZone:"Asia/Tehran",weekday:"long",day:"numeric",month:"long",hour:"2-digit",minute:"2-digit"}).format(new Date())}
function errorInfo(result){if(result?.status!=="rejected")return null;const e=result.reason;return{code:e?.code||"API_ERROR",message:e?.message||"درخواست ناموفق بود."}}
function normalizeTeamName(name){return String(name||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim().replace(/\b(fc|sc|club|sazi)\b/g,"").replace(/\s+/g," ").trim()}
function rankClass(rank){return rank===1?"bg-amber-400 text-slate-950":rank===2?"bg-slate-300 text-slate-950":rank===3?"bg-orange-300 text-slate-950":"bg-white/[.06] text-slate-400"}
function resultForTeam(match,team){const t=normalizeTeamName(team);const home=normalizeTeamName(match.home);const away=normalizeTeamName(match.away);if(t!==home&&t!==away)return null;const hs=Number(match.homeScore);const as=Number(match.awayScore);if(!Number.isFinite(hs)||!Number.isFinite(as))return null;const win=t===home?hs>as:as>hs;const draw=hs===as;return win?"W":draw?"D":"L"}
const tabs=[["overview","خلاصه",BarChart3],["matches","بازی‌ها",CalendarDays],["table","جدول",ListOrdered],["stats","آمار",Goal],["news","اخبار",Newspaper]];

export default async function LeagueDetailPage({params,searchParams}){
 const countryLeague=LEAGUE_ENTRIES.find(x=>x.slug===params.slug);const cup=CLUB_CUPS.find(x=>x.slug===params.slug);if(!countryLeague&&!cup)return <main className="fot-shell"><div className="fot-container py-16 text-center"><h1 className="text-xl font-black">رقابت پیدا نشد</h1><Link href="/leagues" className="text-sm text-cyan-400 mt-4 inline-block">بازگشت به رقابت‌ها</Link></div></main>;
 const league=countryLeague||{name:cup.name,leagueName:cup.name,apiCountry:cup.country,flag:cup.icon,leagueId:cup.id};const today=tehranToday();const debug=searchParams?.debug==="1";const activeTab=tabs.some(([id])=>id===searchParams?.tab)?searchParams.tab:"overview";const tableMode=searchParams?.table==="summary"?"summary":"full";
 let matches=[],seasonMatches=[],standings=[],scorers=[],assists=[],season=null,liveError=null,resolved=null;let diagnostics=[];
 try{resolved=league.leagueId?{league:{id:league.leagueId,name:league.leagueName},source:"configured"}:await getLeagueByCountry(league.apiCountry,league.leagueName);const leagueId=resolved?.league?.id;if(!leagueId)throw new Error("league unavailable");season=Number(leagueId)===195?2026:await getLeagueCurrentSeason(leagueId);const results=await Promise.allSettled([getMatchesResilient({date:today,league:leagueId,season}),getMatchesResilient({league:leagueId,season}),getStandingsResilient(leagueId,season),getPlayerStatsResilient("scorers",leagueId,season,getTopScorers),getPlayerStatsResilient("assists",leagueId,season,getTopAssists)]);if(results[0].status==="fulfilled")matches=results[0].value.data||[];if(results[1].status==="fulfilled")seasonMatches=results[1].value.data||[];if(results[2].status==="fulfilled")standings=results[2].value.data||[];if(results[3].status==="fulfilled")scorers=results[3].value.data||[];if(results[4].status==="fulfilled")assists=results[4].value.data||[];diagnostics=results.map((r,i)=>{const names=["بازی‌های امروز","بازی‌های فصل","جدول","گلزنان","پاس گل"];if(r.status!=="fulfilled")return{name:names[i],ok:false,error:errorInfo(r)};return{name:names[i],ok:true,count:r.value?.data?.length||0,source:r.value?.source,fallback:r.value?.fallback}});if(diagnostics.some(x=>x.fallback))liveError="بخشی از داده‌ها با سرویس جایگزین مطمئن نمایش داده شد."}catch(e){liveError=e instanceof Error?e.message:"live data unavailable"}
 const rows=(standings||[]).flatMap(x=>{const g=x?.league?.standings||[];return g.flat?g.flat():g}).filter(Boolean);const finished=seasonMatches.filter(m=>["FT","AET","PEN"].includes(m.statusShort)).sort((a,b)=>new Date(b.date)-new Date(a.date));const upcoming=seasonMatches.filter(m=>m?.date&&new Date(m.date)>new Date()&&!(["FT","AET","PEN"].includes(m.statusShort))).sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(0,10);
 const teamLogoMap=new Map();for(const m of seasonMatches){if(m?.home&&m?.homeLogo)teamLogoMap.set(normalizeTeamName(m.home),m.homeLogo);if(m?.away&&m?.awayLogo)teamLogoMap.set(normalizeTeamName(m.away),m.awayLogo)}const getTeamLogo=name=>teamLogoMap.get(normalizeTeamName(name))||null;
 const formRows=rows.map(r=>{const name=r.team?.name||"";const form=finished.filter(m=>resultForTeam(m,name)).slice(0,5).map(m=>({result:resultForTeam(m,name),date:m.date}));return {...r,form}});
 const displayCountry=countryLeague?`${countryLeague.flag} ${countryLeague.name}`:league.apiCountry;const statCards=[["بازی امروز",matches.length,CalendarDays],["تیم‌ها",rows.length||"—",Trophy],["گلزنان",scorers.length||"—",Goal],["پاسورها",assists.length||"—",Hand]];const bestAttack=rows.filter(r=>Number.isFinite(Number(r.all?.goals?.for))).sort((a,b)=>(b.all.goals.for||0)-(a.all.goals.for||0))[0];const bestDefense=rows.filter(r=>Number.isFinite(Number(r.all?.goals?.against))).sort((a,b)=>(a.all.goals.against||0)-(b.all.goals.against||0))[0];const mostWins=rows.filter(r=>Number.isFinite(Number(r.all?.win))).sort((a,b)=>(b.all.win||0)-(a.all.win||0))[0];const playerHref=x=>x?.player?.id&&!String(x.player.id).startsWith("iran-")?`/players/${x.player.id}`:null;
 return <main className="fot-shell min-h-screen pb-10"><div className="fot-container space-y-4 sm:space-y-5">
 <header className="flex items-center gap-3 pt-1"><Link href="/leagues" className="glass h-10 w-10 rounded-xl grid place-items-center hover:bg-white/10 transition"><ArrowRight size={19}/></Link><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-emerald-400"/><span className="text-[10px] text-emerald-300 font-bold">رقابت فعال</span></div><h1 className="text-lg sm:text-xl font-black truncate">{league.flag} {league.leagueName}</h1><p className="text-[10px] text-slate-500">{displayCountry} · فصل {season}</p></div><FavoriteButton type="league" name={league.leagueName||""} className="shrink-0"/></header>
 <section className="relative overflow-hidden rounded-[26px] border border-white/10 bg-gradient-to-br from-cyan-400/[.16] via-slate-900/80 to-slate-950 p-5 sm:p-7 shadow-2xl"><div className="relative flex flex-col sm:flex-row sm:items-center gap-5"><div className="h-20 w-20 sm:h-24 sm:w-24 rounded-3xl bg-white/[.08] border border-white/10 grid place-items-center text-5xl shrink-0">{league.flag}</div><div className="min-w-0 flex-1"><div className="flex gap-2 mb-2"><span className="rounded-full bg-cyan-400/10 border border-cyan-300/20 px-2.5 py-1 text-[9px] text-cyan-200">فوتبال</span><span className="rounded-full bg-white/[.06] px-2.5 py-1 text-[9px] text-slate-400">فصل {season}</span></div><h2 className="text-2xl sm:text-3xl font-black truncate">{league.leagueName}</h2><p className="text-[11px] text-slate-400 mt-2">{displayCountry} · داده‌های رقابت</p><p className="text-[9px] text-slate-500 mt-2">آخرین بررسی FOT10: {formatChecked()}</p></div></div><div className="relative mt-6 grid grid-cols-2 sm:grid-cols-4 gap-2.5">{statCards.map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-white/5 bg-black/20 p-3.5"><div className="flex justify-between"><span className="text-[9px] text-slate-500">{label}</span><Icon size={14} className="text-cyan-300"/></div><b className="block text-xl mt-2">{value}</b></div>)}</div></section>
 <nav className="glass rounded-2xl p-1 grid grid-cols-5 gap-1 sticky top-2 z-20 backdrop-blur-xl">{tabs.map(([id,label,Icon])=><Link key={id} href={`/leagues/${params.slug}?tab=${id}`} className={`rounded-xl px-1 py-2.5 text-[9px] sm:text-[11px] font-bold text-center flex flex-col items-center gap-1 transition ${activeTab===id?"bg-cyan-400 text-slate-950 shadow-lg":"text-slate-400 hover:bg-white/5"}`}><Icon size={15}/>{label}</Link>)}</nav>
 {liveError&&<div className="glass rounded-2xl p-3 text-center text-[10px] text-amber-300">{liveError}</div>}
 {debug&&<section className="rounded-2xl bg-slate-950 border border-slate-700 p-4 font-mono text-[11px] space-y-2" dir="ltr"><p className="text-yellow-300 font-bold">FOT10 API diagnostic</p><p>leagueId: {resolved?.league?.id??league.leagueId} · season: {season} · date: {today}</p>{diagnostics.map(x=><div key={x.name} className={x.ok?"text-emerald-300":"text-red-300"}>{x.name}: {x.ok?`OK (${x.count})`:x.error?.code||"NO_DATA"}{x.source?` · ${x.source}${x.fallback?" · FALLBACK":""}`:""}</div>)}</section>}
 {(activeTab==="overview"||activeTab==="matches")&&<section className="space-y-2.5"><div className="flex items-end justify-between px-1"><div><p className="text-[9px] text-cyan-300 font-bold">MATCH CENTER</p><h2 className="flex items-center gap-2 text-base font-black mt-1"><CalendarDays size={17}/> بازی‌های امروز</h2></div><span className="rounded-lg bg-white/[.04] px-2 py-1 text-[9px] text-slate-500">{today}</span></div>{matches.length?matches.slice(0,12).map(m=><Link key={m.id} href={`/matches/${m.id}`} className="group glass rounded-2xl p-3.5 flex items-center gap-3 hover:bg-white/[.06] transition"><div className="h-10 w-10 rounded-xl bg-white/[.05] grid place-items-center overflow-hidden">{m.homeLogo?<img src={m.homeLogo} alt="" className="h-8 w-8 object-contain"/>:"⚽"}</div><div className="flex-1 min-w-0"><b className="block text-xs truncate">{m.home}</b><b className="block text-xs mt-1 truncate">{m.away}</b></div><div className="text-left"><span className="rounded-lg bg-white/[.05] px-2.5 py-1.5 text-[10px] font-bold">{m.statusShort==="NS"?formatTime(m.date):`${m.homeScore??0} - ${m.awayScore??0}`}</span><ChevronLeft size={13} className="ml-auto mt-2 text-slate-600 group-hover:text-cyan-300"/></div></Link>):<div className="glass rounded-2xl p-7 text-center text-xs text-slate-500">امروز بازی ثبت‌شده‌ای پیدا نشد.</div>}<div className="flex items-end justify-between px-1 pt-3"><div><p className="text-[9px] text-amber-300 font-bold">UPCOMING</p><h2 className="flex items-center gap-2 text-base font-black mt-1"><Clock3 size={17}/> بازی‌های آینده</h2></div></div>{upcoming.length?upcoming.map(m=>{const homeLogo=m.homeLogo||getTeamLogo(m.home);const awayLogo=m.awayLogo||getTeamLogo(m.away);return <Link key={`up-${m.id}`} href={`/matches/${m.id}`} className="group glass rounded-2xl p-3.5 hover:bg-white/[.06] transition"><div className="text-[9px] text-amber-300"><CalendarDays size={12} className="inline mr-1"/>{formatDate(m.date)} · {formatTime(m.date)}</div><div className="mt-2 grid grid-cols-[1fr_auto_1fr] items-center gap-2"><div className="flex items-center gap-2 min-w-0"><span className="h-8 w-8 shrink-0 rounded-xl bg-white/[.05] grid place-items-center overflow-hidden">{homeLogo?<img src={homeLogo} alt="" className="h-7 w-7 object-contain"/>:"⚽"}</span><b className="text-xs truncate">{m.home}</b></div><span className="text-[9px] text-slate-600">مقابل</span><div className="flex items-center justify-end gap-2 min-w-0"><b className="text-xs truncate text-right">{m.away}</b><span className="h-8 w-8 shrink-0 rounded-xl bg-white/[.05] grid place-items-center overflow-hidden">{awayLogo?<img src={awayLogo} alt="" className="h-7 w-7 object-contain"/>:"⚽"}</span></div></div></Link>}) : <div className="glass rounded-2xl p-7 text-center text-xs text-slate-500">بازی آینده‌ای در داده‌های فعلی پیدا نشد.</div>}</section>}
 {(activeTab==="overview"||activeTab==="table")&&<section className="space-y-2.5"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-2 px-1"><div><p className="text-[9px] text-cyan-300 font-bold">STANDINGS</p><h2 className="flex items-center gap-2 text-base font-black mt-1"><Trophy size={17}/> جدول حرفه‌ای</h2></div><div className="flex items-center gap-1 rounded-xl bg-white/[.04] p-1"><Link href={`/leagues/${params.slug}?tab=table&table=full`} className={`rounded-lg px-3 py-1.5 text-[9px] font-bold ${tableMode==="full"?"bg-cyan-400 text-slate-950":"text-slate-500"}`}>کامل</Link><Link href={`/leagues/${params.slug}?tab=table&table=summary`} className={`rounded-lg px-3 py-1.5 text-[9px] font-bold ${tableMode==="summary"?"bg-cyan-400 text-slate-950":"text-slate-500"}`}>خلاصه</Link></div></div>{rows.length?<div className="glass rounded-[22px] overflow-hidden border border-white/5"><div className="hidden sm:grid grid-cols-[2.5rem_1fr_3rem_3rem_3rem_3rem_4rem] gap-2 px-4 py-2.5 text-[8px] text-slate-600 border-b border-white/5"><span>#</span><span>تیم</span><span>بازی</span><span>برد</span><span>مساوی</span><span>تفاضل</span><span className="text-left">امتیاز</span></div>{rows.map((r,i)=>{const teamLogo=r.team?.logo||getTeamLogo(r.team?.name);return <Link key={`${r.team?.id||"team"}-${i}`} href={r.team?.id&&!String(r.team.id).startsWith("iran-")?`/teams/${r.team.id}`:"/teams"} className="group grid grid-cols-[2.2rem_1fr_3rem_3rem_3rem_3.5rem] sm:grid-cols-[2.5rem_1fr_3rem_3rem_3rem_3rem_4rem] gap-2 px-3.5 sm:px-4 py-3 border-b border-white/5 last:border-0 items-center hover:bg-white/[.04] transition"><span className={`h-7 w-7 rounded-lg grid place-items-center text-[10px] font-black ${rankClass(r.rank||i+1)}`}>{r.rank||i+1}</span><span className="min-w-0 flex items-center gap-2.5"><span className="h-8 w-8 shrink-0 rounded-xl bg-white/[.05] grid place-items-center overflow-hidden">{teamLogo?<img src={teamLogo} alt="" className="h-7 w-7 object-contain"/>:"⚽"}</span><span className="truncate text-xs font-semibold">{r.team?.name||"تیم نامشخص"}</span></span><span className="text-xs text-slate-400">{r.all?.played??0}</span><span className="text-xs text-slate-400">{r.all?.win??0}</span><span className="text-xs text-slate-400">{r.all?.draw??0}</span><span className="text-xs text-slate-400">{r.goalsDiff>0?`+${r.goalsDiff}`:r.goalsDiff??0}</span><b className="text-left text-sm group-hover:text-cyan-300">{r.points??0}</b></Link>})}</div>:<div className="glass rounded-2xl p-5 text-center text-sm text-slate-500">جدول فعلاً داده‌ای برنگرداند.</div>}
 {rows.length>0&&<div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 pt-1">{[["بهترین حمله",bestAttack?.team?.name,bestAttack?.all?.goals?.for,Zap],["بهترین دفاع",bestDefense?.team?.name,bestDefense?.all?.goals?.against,Shield],["بیشترین برد",mostWins?.team?.name,mostWins?.all?.win,Trophy]].map(([label,name,value,Icon])=><div key={label} className="glass rounded-2xl p-3.5 border border-white/5"><div className="flex items-center gap-2 text-[9px] text-slate-500"><Icon size={14} className="text-cyan-300"/>{label}</div><b className="block text-xs mt-2 truncate">{name||"—"}</b><span className="text-[10px] text-cyan-200">{value??"—"}</span></div>)}</div>}</section>}
 {(activeTab==="overview"||activeTab==="stats")&&<section className="space-y-3"><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{[["گلزنان برتر",scorers,Goal,"goals"],["پاس گل",assists,Hand,"assists"]].map(([title,list,Icon,type])=><div key={title} className="glass rounded-[22px] p-4 border border-white/5"><div className="flex justify-between mb-3"><div><p className="text-[9px] text-cyan-300 font-bold">{type==="goals"?"TOP SCORERS":"TOP ASSISTS"}</p><h2 className="flex items-center gap-2 text-sm font-black mt-1"><Icon size={16}/>{title}</h2></div><TrendingUp size={16} className="text-slate-600"/></div>{list.slice(0,5).map((item,i)=>{const href=playerHref(item);const content=<><span className={`h-6 w-6 rounded-lg grid place-items-center text-[9px] font-black ${i===0?"bg-amber-400 text-slate-950":"bg-white/[.05] text-slate-500"}`}>{i+1}</span><span className="min-w-0 flex-1 text-xs font-semibold truncate">{item.player?.name}</span><b className="rounded-lg bg-cyan-400/10 px-2 py-1 text-xs text-cyan-200">{type==="goals"?item.statistics?.[0]?.goals?.total??0:item.statistics?.[0]?.goals?.assists??0}</b></>;return href?<Link key={`${item.player?.id}-${i}`} href={href} className="flex items-center gap-2.5 py-2.5 border-b border-white/5 last:border-0">{content}</Link>:<div key={`${item.player?.id}-${i}`} className="flex items-center gap-2.5 py-2.5 border-b border-white/5 last:border-0">{content}</div>})}</div>)}</div>
 <div className="glass rounded-[22px] p-4 border border-white/5"><div className="flex items-center gap-2 mb-3"><Activity size={16} className="text-cyan-300"/><div><p className="text-[9px] text-cyan-300 font-bold">TEAM FORM</p><h2 className="text-sm font-black">فرم ۵ بازی اخیر تیم‌ها</h2></div></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{formRows.slice(0,10).map(r=><div key={r.team?.id||r.team?.name} className="rounded-xl bg-white/[.03] border border-white/5 px-3 py-2.5 flex items-center gap-2"><span className="h-7 w-7 rounded-lg bg-white/[.05] grid place-items-center overflow-hidden">{getTeamLogo(r.team?.name)?<img src={getTeamLogo(r.team?.name)} alt="" className="h-6 w-6 object-contain"/>:"⚽"}</span><span className="min-w-0 flex-1 text-[10px] font-semibold truncate">{r.team?.name}</span><span className="flex gap-1">{r.form.map((f,i)=><span key={`${f.date}-${i}`} className={`h-5 w-5 rounded-md grid place-items-center text-[8px] font-black ${f.result==="W"?"bg-emerald-400/20 text-emerald-300":f.result==="D"?"bg-amber-400/20 text-amber-300":"bg-rose-400/20 text-rose-300"}`}>{f.result}</span>)}{!r.form.length&&<span className="text-[9px] text-slate-600">بدون داده</span>}</span></div>)}</div></div></section>}
 {activeTab==="news"&&<section className="space-y-3"><div className="glass rounded-[24px] p-5 border border-white/5"><div className="flex items-center gap-3"><span className="h-11 w-11 rounded-2xl bg-cyan-400/10 grid place-items-center"><Newspaper size={21} className="text-cyan-300"/></span><div><p className="text-[9px] text-cyan-300 font-bold">NEWS CENTER</p><h2 className="text-lg font-black">مرکز اخبار فوتبال ایران</h2><p className="text-[10px] text-slate-500 mt-1">برای جلوگیری از خبرسازی، FOT10 خبر را فقط از منابع خبری واقعی نمایش می‌دهد.</p></div></div></div><a href="https://footbaliran.com/en/latest" target="_blank" rel="noreferrer" className="glass rounded-2xl p-4 flex items-center gap-3 hover:bg-white/[.06] transition"><span className="h-10 w-10 rounded-xl bg-white/[.05] grid place-items-center"><Newspaper size={17}/></span><div className="min-w-0 flex-1"><b className="block text-sm">آخرین اخبار Football Iran</b><span className="text-[10px] text-slate-500">اخبار و پوشش روز فوتبال ایران</span></div><ChevronLeft size={17} className="text-slate-600"/></a><a href="https://www.persianleague.com/44-all-news" target="_blank" rel="noreferrer" className="glass rounded-2xl p-4 flex items-center gap-3 hover:bg-white/[.06] transition"><span className="h-10 w-10 rounded-xl bg-white/[.05] grid place-items-center">📰</span><div className="min-w-0 flex-1"><b className="block text-sm">PersianLeague News</b><span className="text-[10px] text-slate-500">نتایج و اخبار لیگ‌های ایران</span></div><ChevronLeft size={17} className="text-slate-600"/></a></section>}
 </div></main>
}
