import Link from "next/link";
import { ArrowRight, CalendarDays, Trophy, Goal, Hand, BarChart3, ListOrdered } from "lucide-react";
import { CLUB_CUPS, LEAGUE_ENTRIES } from "../../../lib/fot10-universe";
import { getLeagueByCountry, getLeagueCurrentSeason, getTopScorers, getTopAssists } from "../../../lib/sports-data";
import { getMatchesResilient, getStandingsResilient } from "../../../lib/football-resilient";
import FavoriteButton from "../../../components/FavoriteButton";

export const dynamic = "force-dynamic";
function tehranToday() { return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran" }).format(new Date()); }
function formatTime(date) { return new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit" }).format(new Date(date)); }
function errorInfo(result) { if (result?.status !== "rejected") return null; const error = result.reason; return { code: error?.code || "API_ERROR", message: error?.message || "درخواست ناموفق بود.", status: error?.details?.status || null, dailyRemaining: error?.details?.dailyRemaining || null }; }
const tabs = [["overview", "خلاصه", BarChart3], ["matches", "بازی‌ها", CalendarDays], ["table", "جدول", ListOrdered], ["stats", "آمار", Goal]];

export default async function LeagueDetailPage({ params, searchParams }) {
  const countryLeague = LEAGUE_ENTRIES.find((item) => item.slug === params.slug); const cup = CLUB_CUPS.find((item) => item.slug === params.slug);
  if (!countryLeague && !cup) return <main className="fot-shell"><div className="fot-container py-16 text-center"><h1 className="text-xl font-black">رقابت پیدا نشد</h1><Link href="/leagues" className="text-sm text-cyan-400 mt-4 inline-block">بازگشت به رقابت‌ها</Link></div></main>;
  const league = countryLeague || { name: cup.name, leagueName: cup.name, apiCountry: cup.country, flag: cup.icon, leagueId: cup.id }; const today = tehranToday(); const debug = searchParams?.debug === "1"; const activeTab = tabs.some(([id]) => id === searchParams?.tab) ? searchParams.tab : "overview";
  let matches = [], standings = [], scorers = [], assists = [], season = null, liveError = null, resolved = null, standingsMeta = null, matchesMeta = null; let diagnostics = [];
  try {
    resolved = league.leagueId ? { league: { id: league.leagueId, name: league.leagueName }, source: "configured" } : await getLeagueByCountry(league.apiCountry, league.leagueName);
    const leagueId = resolved?.league?.id; if (!leagueId) throw new Error("league unavailable");
    season = Number(leagueId) === 195 ? 2026 : await getLeagueCurrentSeason(leagueId);
    if (!season) throw new Error("season unavailable");
    const results = await Promise.allSettled([
      getMatchesResilient({ date: today, league: leagueId, season }),
      getStandingsResilient(leagueId, season),
      getTopScorers(leagueId, season),
      getTopAssists(leagueId, season),
    ]);
    if (results[0].status === "fulfilled") { matchesMeta = results[0].value; matches = matchesMeta.data || []; }
    if (results[1].status === "fulfilled") { standingsMeta = results[1].value; standings = standingsMeta.data || []; }
    scorers = results[2].status === "fulfilled" ? results[2].value : [];
    assists = results[3].status === "fulfilled" ? results[3].value : [];
    diagnostics = results.map((result, index) => {
      const names = ["بازی‌ها", "جدول", "گلزنان", "پاس گل"];
      if (index === 0 && result.status === "fulfilled") return { name: names[index], ok: true, count: result.value.data.length, source: result.value.source, fallback: result.value.fallback };
      if (index === 1 && result.status === "fulfilled") return { name: names[index], ok: result.value.data.length > 0, count: result.value.data.length, source: result.value.source, fallback: result.value.fallback, error: result.value.errors?.length ? result.value.errors : null };
      return { name: names[index], ok: result.status === "fulfilled", count: result.status === "fulfilled" ? result.value?.length || 0 : 0, error: errorInfo(result) };
    });
    if (matchesMeta?.fallback || standingsMeta?.fallback) liveError = "داده از سرویس جایگزین مطمئن نمایش داده شد.";
  } catch (error) { liveError = error instanceof Error ? error.message : "live data unavailable"; }
  const rows = (standings || []).flatMap((item) => { const groups = item?.league?.standings || []; return groups.flat ? groups.flat() : groups; }).filter(Boolean);
  const displayCountry = countryLeague ? `${countryLeague.flag} ${countryLeague.name}` : league.apiCountry;
  const matchList = matches.slice(0, 12);
  const statCards = [["بازی امروز", matches.length], ["تیم‌ها", rows.length || "—"], ["گلزنان", scorers.length || "—"], ["پاسورها", assists.length || "—"]];
  return <main className="fot-shell"><div className="fot-container space-y-5">
    <header className="flex items-center gap-3"><Link href="/leagues" aria-label="بازگشت" className="glass h-10 w-10 rounded-xl grid place-items-center"><ArrowRight size={19}/></Link><div className="min-w-0 flex-1"><h1 className="text-xl font-black truncate">{league.flag} {league.leagueName}</h1><p className="text-[11px] text-slate-500 truncate">{displayCountry} · {season ? `فصل ${season}` : "رقابت"}</p></div><FavoriteButton type="league" name={league.leagueName || ""} className="shrink-0" /></header>
    <section className="glass card p-5"><div className="flex items-center gap-3"><span className="text-4xl">{league.flag}</span><div className="min-w-0"><p className="text-xs text-slate-400">رقابت فوتبال</p><h2 className="text-2xl font-black truncate">{league.leagueName}</h2><p className="text-[10px] text-slate-500 mt-1">{displayCountry} {season ? `· فصل ${season}` : ""}</p></div></div><div className="mt-4 grid grid-cols-2 sm:grid-cols-4 gap-2">{statCards.map(([label, value]) => <div key={label} className="rounded-xl bg-white/[.04] p-3"><b className="text-lg">{value}</b><p className="text-[9px] text-slate-500 mt-1">{label}</p></div>)}</div></section>
    <nav className="glass rounded-2xl p-1 grid grid-cols-4 gap-1 sticky top-2 z-10 backdrop-blur-xl">{tabs.map(([id, label, Icon]) => <Link key={id} href={`/leagues/${params.slug}?tab=${id}`} className={`rounded-xl px-2 py-3 text-[11px] font-bold text-center flex flex-col items-center gap-1 transition ${activeTab === id ? "bg-cyan-400 text-slate-950" : "text-slate-400 hover:bg-white/5"}`}><Icon size={15}/>{label}</Link>)}</nav>
    {liveError && <div className="glass rounded-2xl p-4 text-center text-xs text-amber-300">{liveError}</div>}
    {debug && <section className="rounded-2xl bg-slate-950 border border-slate-700 p-4 font-mono text-[11px] text-slate-300 space-y-2" dir="ltr"><p className="text-yellow-300 font-bold">FOT10 API diagnostic</p><p>leagueId: {resolved?.league?.id ?? league.leagueId ?? "unknown"} · season: {season ?? "none"} · date: {today}</p>{diagnostics.map((item) => <div key={item.name} className={item.ok ? "text-emerald-300" : "text-red-300"}>{item.name}: {item.ok ? `OK (${item.count})` : `${item.error?.code || "ERROR"} · HTTP ${item.error?.status ?? "?"} · ${item.error?.message || "failed"}`}{item.source ? ` · source ${item.source}${item.fallback ? " · FALLBACK" : ""}` : ""}</div>)}</section>}
    {(activeTab === "overview" || activeTab === "matches") && <section className="space-y-2"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-black"><CalendarDays size={16}/> بازی‌های امروز</h2><span className="text-[10px] text-slate-500">{today}</span></div>{matchList.length ? matchList.map((match) => <Link key={match.id} href={`/matches/${match.id}`} className="glass rounded-2xl p-4 flex items-center gap-3 hover:bg-white/[.05] transition"><span className="h-9 w-9 shrink-0 grid place-items-center">{match.homeLogo ? <img src={match.homeLogo} alt="" className="h-9 w-9 object-contain"/> : <span>⚽</span>}</span><span className="flex-1 text-right"><b className="block text-sm">{match.home}</b><b className="block text-sm mt-1">{match.away}</b></span><span className="text-xs text-slate-500">{match.statusShort === "NS" ? formatTime(match.date) : `${match.homeScore ?? 0} - ${match.awayScore ?? 0}`}</span></Link>) : <div className="glass rounded-2xl p-5 text-center text-sm text-slate-500">امروز بازی ثبت‌شده‌ای برای این رقابت پیدا نشد.</div>}</section>}
    {(activeTab === "overview" || activeTab === "table") && <section className="space-y-2"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 text-sm font-black"><Trophy size={16}/> جدول فصل</h2><Link href="/teams" className="text-[10px] text-cyan-300">همه تیم‌ها ←</Link></div>{rows.length ? <div className="glass rounded-2xl overflow-hidden"><div className="grid grid-cols-[2rem_1fr_3rem_4rem] gap-2 px-4 py-2 text-[9px] text-slate-500 border-b border-white/5"><span>#</span><span>تیم</span><span>بازی</span><span className="text-left">امتیاز</span></div>{rows.map((row, index) => <Link key={`${row.team?.id ?? "team"}-${index}`} href={row.team?.id ? `/teams/${row.team.id}` : "/teams"} className="grid grid-cols-[2rem_1fr_3rem_4rem] gap-2 px-4 py-3 border-b border-white/5 last:border-0 items-center text-xs hover:bg-white/[.05] transition"><b>{row.rank}</b><span className="truncate flex items-center gap-2"><span className="h-7 w-7 shrink-0 rounded-lg bg-white/5 grid place-items-center overflow-hidden">{row.team?.logo ? <img src={row.team.logo} alt="" className="h-6 w-6 object-contain"/> : <span className="text-[9px] text-slate-600">⚽</span>}</span><span className="truncate">{row.team?.name || "تیم نامشخص"}</span></span><span className="text-slate-400">{row.all?.played ?? 0}</span><b className="text-left">{row.points ?? 0}</b></Link>)}</div> : <div className="glass rounded-2xl p-5 text-center text-sm text-slate-500">جدول این رقابت فعلاً داده‌ای برنگرداند.</div>}</section>}
    {(activeTab === "overview" || activeTab === "stats") && <section className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div className="glass rounded-2xl p-4"><h2 className="flex items-center gap-2 text-sm font-black mb-3"><Goal size={16}/> گلزنان برتر</h2>{scorers.slice(0, 5).map((item, i) => <Link key={`${item.player?.id}-${i}`} href={`/players/${item.player?.id}`} className="flex items-center gap-2 py-2 border-b border-white/5 last:border-0"><span className="text-[10px] text-slate-500 w-4">{i + 1}</span><span className="min-w-0 flex-1 text-xs truncate">{item.player?.name}</span><b className="text-xs">{item.statistics?.[0]?.goals?.total ?? 0}</b></Link>)}{!scorers.length && <p className="text-xs text-slate-500">داده‌ای موجود نیست.</p>}</div><div className="glass rounded-2xl p-4"><h2 className="flex items-center gap-2 text-sm font-black mb-3"><Hand size={16}/> پاس گل</h2>{assists.slice(0, 5).map((item, i) => <Link key={`${item.player?.id}-${i}`} href={`/players/${item.player?.id}`} className="flex items-center gap-2 py-2 border-b border-white/5 last:border-0"><span className="text-[10px] text-slate-500 w-4">{i + 1}</span><span className="min-w-0 flex-1 text-xs truncate">{item.player?.name}</span><b className="text-xs">{item.statistics?.[0]?.goals?.assists ?? 0}</b></Link>)}{!assists.length && <p className="text-xs text-slate-500">داده‌ای موجود نیست.</p>}</div></section>}
  </div></main>;
}
