import Link from "next/link";
import { ArrowRight, Bell, CalendarDays, ChevronLeft, Clock3, Trophy } from "lucide-react";
import MatchCenterRefresh from "./MatchCenterRefresh";
import { CLUB_CUPS, LEAGUE_ENTRIES } from "../../../../lib/fot10-universe";
import { getMatchesResilient } from "../../../../lib/football-resilient";

export const dynamic = "force-dynamic";

const iranTeamNames = {
  Tractor: "تراکتور", Paykan: "پیکان", Kheybar: "خیبر", "Fajr Sepasi": "فجر سپاسی",
  Esteghlal: "استقلال", "Mes Shahr": "مس شهر بابک", "Chadormalu SC": "چادرملو", Sepahan: "سپاهان",
  "Esteghlal Khuzestan": "استقلال خوزستان", "Aluminium Arak": "آلومینیوم اراک", "Gol Gohar FC": "گل‌گهر",
  Nassaji: "نساجی", "Zob Ahan": "ذوب‌آهن", Foolad: "فولاد", "Shams Azar": "شمس‌آذر",
  Persepolis: "پرسپولیس", "Sanat Naft": "صنعت نفت آبادان", Malavan: "ملوان",
};
function faTeam(name) { return iranTeamNames[name] || name; }

const iranSchedule = {
  1: [["چادرملو","سپاهان"],["صنعت نفت آبادان","ملوان"],["خیبر","فجر سپاسی"],["استقلال","مس شهر بابک"],["ذوب‌آهن","فولاد"],["گل‌گهر","نساجی"],["شمس‌آذر","پرسپولیس"],["استقلال خوزستان","آلومینیوم اراک"],["تراکتور","پیکان"]],
  2: [["آلومینیوم اراک","چادرملو"],["سپاهان","تراکتور"],["پیکان","گل‌گهر"],["پرسپولیس","استقلال خوزستان"],["فولاد","شمس‌آذر"],["نساجی","استقلال"],["فجر سپاسی","صنعت نفت آبادان"],["ملوان","ذوب‌آهن"],["مس شهر بابک","خیبر"]],
  3: [["استقلال","سپاهان"],["گل‌گهر","چادرملو"],["ملوان","فجر سپاسی"],["ذوب‌آهن","مس شهر بابک"],["صنعت نفت آبادان","فولاد"],["استقلال خوزستان","نساجی"],["تراکتور","پرسپولیس"],["شمس‌آذر","آلومینیوم اراک"],["خیبر","پیکان"]],
  4: [["پرسپولیس","ملوان"],["چادرملو","تراکتور"],["سپاهان","گل‌گهر"],["پیکان","استقلال خوزستان"],["نساجی","شمس‌آذر"],["فولاد","استقلال"],["مس شهر بابک","صنعت نفت آبادان"],["فجر سپاسی","ذوب‌آهن"],["آلومینیوم اراک","خیبر"]],
  5: [["صنعت نفت آبادان","سپاهان"],["استقلال خوزستان","چادرملو"],["شمس‌آذر","تراکتور"],["فجر سپاسی","مس شهر بابک"],["خیبر","فولاد"],["ملوان","نساجی"],["استقلال","پرسپولیس"],["گل‌گهر","آلومینیوم اراک"],["ذوب‌آهن","پیکان"]],
  6: [["مس شهر بابک","ملوان"],["فولاد","فجر سپاسی"],["تراکتور","گل‌گهر"],["سپاهان","استقلال خوزستان"],["چادرملو","شمس‌آذر"],["آلومینیوم اراک","استقلال"],["پیکان","صنعت نفت آبادان"],["پرسپولیس","ذوب‌آهن"],["نساجی","خیبر"]],
  7: [["ذوب‌آهن","سپاهان"],["صنعت نفت آبادان","چادرملو"],["استقلال خوزستان","تراکتور"],["شمس‌آذر","گل‌گهر"],["ملوان","فولاد"],["مس شهر بابک","نساجی"],["خیبر","پرسپولیس"],["فجر سپاسی","آلومینیوم اراک"],["استقلال","پیکان"]],
  8: [["آلومینیوم اراک","ملوان"],["سپاهان","فجر سپاسی"],["فولاد","مس شهر بابک"],["گل‌گهر","استقلال خوزستان"],["پیکان","شمس‌آذر"],["تراکتور","استقلال"],["پرسپولیس","صنعت نفت آبادان"],["نساجی","ذوب‌آهن"],["چادرملو","خیبر"]],
  9: [["شمس‌آذر","سپاهان"],["ذوب‌آهن","چادرملو"],["ملوان","تراکتور"],["استقلال","گل‌گهر"],["خیبر","استقلال خوزستان"],["فولاد","نساجی"],["مس شهر بابک","پرسپولیس"],["صنعت نفت آبادان","آلومینیوم اراک"],["فجر سپاسی","پیکان"]],
  10: [["پیکان","ملوان"],["نساجی","فجر سپاسی"],["سپاهان","مس شهر بابک"],["پرسپولیس","فولاد"],["استقلال خوزستان","شمس‌آذر"],["چادرملو","استقلال"],["تراکتور","صنعت نفت آبادان"],["آلومینیوم اراک","ذوب‌آهن"],["گل‌گهر","خیبر"]],
  11: [["خیبر","سپاهان"],["ملوان","چادرملو"],["فجر سپاسی","تراکتور"],["صنعت نفت آبادان","گل‌گهر"],["ذوب‌آهن","استقلال خوزستان"],["استقلال","شمس‌آذر"],["نساجی","پرسپولیس"],["فولاد","آلومینیوم اراک"],["مس شهر بابک","پیکان"]],
  12: [["سپاهان","ملوان"],["پرسپولیس","فجر سپاسی"],["آلومینیوم اراک","مس شهر بابک"],["چادرملو","فولاد"],["پیکان","نساجی"],["استقلال خوزستان","استقلال"],["شمس‌آذر","صنعت نفت آبادان"],["گل‌گهر","ذوب‌آهن"],["تراکتور","خیبر"]],
  13: [["فولاد","سپاهان"],["فجر سپاسی","چادرملو"],["مس شهر بابک","تراکتور"],["ملوان","گل‌گهر"],["صنعت نفت آبادان","استقلال خوزستان"],["ذوب‌آهن","شمس‌آذر"],["خیبر","استقلال"],["نساجی","آلومینیوم اراک"],["پرسپولیس","پیکان"]],
  14: [["استقلال خوزستان","ملوان"],["گل‌گهر","فجر سپاسی"],["چادرملو","مس شهر بابک"],["پیکان","فولاد"],["سپاهان","نساجی"],["آلومینیوم اراک","پرسپولیس"],["استقلال","صنعت نفت آبادان"],["تراکتور","ذوب‌آهن"],["شمس‌آذر","خیبر"]],
  15: [["پرسپولیس","سپاهان"],["نساجی","چادرملو"],["فولاد","تراکتور"],["مس شهر بابک","گل‌گهر"],["فجر سپاسی","استقلال خوزستان"],["ملوان","شمس‌آذر"],["ذوب‌آهن","استقلال"],["آلومینیوم اراک","پیکان"],["صنعت نفت آبادان","خیبر"]],
  16: [["خیبر","ملوان"],["استقلال","فجر سپاسی"],["شمس‌آذر","مس شهر بابک"],["استقلال خوزستان","فولاد"],["تراکتور","نساجی"],["گل‌گهر","پرسپولیس"],["سپاهان","آلومینیوم اراک"],["چادرملو","پیکان"],["صنعت نفت آبادان","ذوب‌آهن"]],
  17: [["پیکان","سپاهان"],["پرسپولیس","چادرملو"],["آلومینیوم اراک","تراکتور"],["فولاد","گل‌گهر"],["مس شهر بابک","استقلال خوزستان"],["فجر سپاسی","شمس‌آذر"],["ملوان","استقلال"],["نساجی","صنعت نفت آبادان"],["ذوب‌آهن","خیبر"]],
};

function formatDate(date) { if (!date) return "زمان اعلام می‌شود"; return new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", weekday: "short", day: "numeric", month: "long" }).format(new Date(date)); }
function formatTime(date) { if (!date) return ""; return new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit" }).format(new Date(date)); }
function getWeek(match) { const raw = String(match?.round || match?.week || match?.matchweek || "").toLowerCase(); const numbers = raw.match(/\d{1,2}/g); return numbers?.length ? Number(numbers[numbers.length - 1]) : null; }
function normalizeTeamKey(name) { return String(name || "").replace(/[يى]/g, "ی").replace(/[ك]/g, "ک").replace(/[‌\s-]/g, "").toLowerCase(); }
function fallbackRows(week) { return (iranSchedule[week] || []).map(([home, away], i) => ({ id: `iran-${week}-${i + 1}`, home, away, date: null, homeScore: null, awayScore: null, statusShort: "NS", _week: week, _fallback: true })); }
function mergeWeekRows(week, apiRows) { const scheduleRows = fallbackRows(week); const result = scheduleRows.map(fallback => { const match = apiRows.find(api => normalizeTeamKey(faTeam(api.home)) === normalizeTeamKey(fallback.home) && normalizeTeamKey(faTeam(api.away)) === normalizeTeamKey(fallback.away)); return match ? { ...fallback, ...match, _week: week, _fallback: false } : fallback; }); for (const api of apiRows) { if (!result.some(row => row.id === api.id)) result.push({ ...api, _week: week, _fallback: false }); } return result; }

export default async function LeagueMatchesPage({ params, searchParams }) {
  const league = LEAGUE_ENTRIES.find(x => x.slug === params.slug); const cup = CLUB_CUPS.find(x => x.slug === params.slug);
  if (!league && !cup) return <main className="fot-shell"><div className="fot-container py-20 text-center">رقابت پیدا نشد</div></main>;
  const item = league || { leagueName: cup.name, leagueId: cup.id, flag: cup.icon, name: cup.name };
  const requested = String(searchParams?.week || "1").toLowerCase(); const showAll = requested === "all"; const selected = showAll ? null : Math.min(17, Math.max(1, Number(requested) || 1));
  let matches = [];
  if (item.leagueId) { try { const result = await getMatchesResilient({ league: item.leagueId, season: Number(item.leagueId) === 195 ? 2026 : undefined }); matches = result?.data || []; } catch {} }
  const normalized = matches.map(m => ({ ...m, _week: getWeek(m) }));
  const buildWeekRows = week => { const apiRows = normalized.filter(m => m._week === week).sort((a, b) => new Date(a.date || 0) - new Date(b.date || 0)); return item.leagueId === 195 ? mergeWeekRows(week, apiRows) : apiRows; };
  const rows = showAll ? Array.from({ length: 17 }, (_, i) => buildWeekRows(i + 1).map(m => ({ ...m, _displayWeek: i + 1 }))).flat() : buildWeekRows(selected);
  const counts = Array.from({ length: 17 }, (_, i) => buildWeekRows(i + 1).length); const finished = rows.filter(m => m.statusShort === "FT" || m.status === "FT" || m.homeScore != null).length; const goals = rows.reduce((s, m) => s + (Number(m.homeScore) || 0) + (Number(m.awayScore) || 0), 0);

  return <main className="fot-shell min-h-screen pb-24"><MatchCenterRefresh/><div className="fot-container space-y-4 sm:space-y-5">
    <header className="flex items-center gap-3 pt-2"><Link href={`/leagues/${params.slug}`} aria-label="بازگشت" className="glass h-10 w-10 rounded-xl grid place-items-center hover:bg-white/10 transition"><ArrowRight size={19}/></Link><div className="min-w-0 flex-1"><p className="text-[9px] text-emerald-400 font-black tracking-[.22em]">FOT10 MATCH CENTER</p><h1 className="text-xl font-black truncate mt-0.5">{item.flag} {item.leagueName}</h1><p className="text-[10px] text-slate-500 mt-1">برنامه و نتایج فصل ۲۰۲۶ · زمان تهران</p></div><Link href="/notifications" aria-label="اعلان‌ها" className="relative glass h-11 w-11 rounded-2xl grid place-items-center hover:bg-white/10 transition"><Bell size={19}/><span className="absolute -top-0.5 -left-0.5 h-2.5 w-2.5 rounded-full bg-emerald-400 ring-2 ring-slate-950"/></Link></header>
    <section className="relative overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-cyan-400/[.13] via-white/[.035] to-transparent p-4 sm:p-5 shadow-2xl"><div className="absolute -top-16 -left-10 h-36 w-36 rounded-full bg-cyan-400/10 blur-3xl pointer-events-none"/><div className="relative flex items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-cyan-300"><Trophy size={15}/><span className="text-[9px] font-black tracking-[.18em]">MATCH CENTER</span></div><h2 className="text-lg sm:text-xl font-black mt-1">{showAll ? "تمام هفته‌ها" : `هفته ${selected}`}</h2><p className="text-[9px] text-slate-500 mt-1">{showAll ? `${rows.length} بازی در برنامه` : `${rows.length} بازی · ${finished} پایان‌یافته · ${goals} گل`}</p></div><div className="rounded-2xl border border-white/10 bg-black/10 px-3 py-2 text-center"><span className="block text-[8px] text-slate-500">SEASON</span><b className="text-sm">۲۰۲۶</b></div></div></section>
    <section className="glass rounded-[24px] border border-white/10 p-2"><div className="flex items-center gap-2 overflow-x-auto pb-1 scrollbar-hide" dir="rtl"><Link href={`/leagues/${params.slug}/matches?week=all`} className={`shrink-0 rounded-xl px-3.5 py-2.5 text-[10px] font-black transition ${showAll ? "bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-400/20" : "bg-white/[.05] text-slate-400 hover:bg-white/10"}`}>همه</Link>{Array.from({length:17},(_,i)=>i+1).map(week=>{const active=!showAll&&selected===week;return <Link key={week} href={`/leagues/${params.slug}/matches?week=${week}`} className={`shrink-0 min-w-[58px] rounded-xl px-2 py-2 text-center transition ${active ? "bg-cyan-400 text-slate-950 shadow-lg shadow-cyan-400/20" : "bg-white/[.05] text-slate-400 hover:bg-white/10"}`}><span className="block text-[10px] font-black">هفته {week}</span><span className={`block text-[8px] mt-0.5 ${active ? "text-slate-800/70" : "text-slate-600"}`}>{counts[week-1]} بازی</span></Link>})}</div></section>
    <section className="glass rounded-[28px] overflow-hidden border border-white/10"><div className="p-4 sm:p-5 border-b border-white/10 bg-gradient-to-r from-cyan-400/[.08] to-transparent flex items-center justify-between gap-3"><div><p className="text-[9px] text-cyan-300 font-black tracking-widest">{showAll ? "ALL MATCHWEEKS" : `MATCHWEEK ${String(selected).padStart(2,"0")}`}</p><h3 className="text-base font-black mt-1">{showAll ? "بازی‌های لیگ" : `هفته ${selected}`}</h3></div><span className="rounded-full bg-white/[.06] px-3 py-1.5 text-[9px] text-slate-400">{rows.length} بازی</span></div>{rows.length ? <div className="divide-y divide-white/[.06]">{rows.map((m,index)=>{const home=faTeam(m.home),away=faTeam(m.away),isFinished=m.statusShort==="FT"||m.status==="FT"||m.homeScore!=null,score=isFinished?`${m.homeScore??0} - ${m.awayScore??0}`:"—",content=<div className="grid grid-cols-[2rem_minmax(0,1fr)_4.2rem_minmax(0,1fr)_6.8rem] items-center gap-2 px-3 py-3.5 sm:px-5 hover:bg-white/[.035] transition"><span className="h-7 w-7 rounded-lg bg-white/[.05] grid place-items-center text-[9px] font-black text-slate-500">{index+1}</span><div className="min-w-0 text-right"><b className="block text-[10px] sm:text-xs truncate">{home}</b><span className="text-[8px] text-slate-600">میزبان</span></div><div className="text-center"><b className={`inline-flex min-w-[42px] justify-center rounded-xl px-2 py-1.5 text-[11px] font-black ${isFinished ? "bg-cyan-400/10 text-cyan-200" : "bg-white/[.06] text-slate-400"}`}>{score}</b><span className={`block text-[7px] mt-1 font-bold ${isFinished ? "text-emerald-400" : "text-slate-600"}`}>{isFinished ? "پایان" : "برنامه"}</span></div><div className="min-w-0 text-right"><b className="block text-[10px] sm:text-xs truncate">{away}</b><span className="text-[8px] text-slate-600">مهمان</span></div><div className="text-left text-[8px] text-slate-400"><span className="flex items-center gap-1 justify-end"><CalendarDays size={11}/>{formatDate(m.date)}</span>{m.date && <span className="flex items-center gap-1 justify-end mt-1"><Clock3 size={11}/>{formatTime(m.date)}</span>}</div></div>;return m.id&&!String(m.id).startsWith("iran-")?<Link key={`${m.id}-${index}`} href={`/matches/${m.id}`}>{content}</Link>:<div key={`${m.id}-${index}`}>{content}</div>})}</div>:<div className="p-10 text-center"><div className="mx-auto mb-3 h-12 w-12 rounded-2xl bg-white/[.04] grid place-items-center text-slate-600"><ChevronLeft size={20}/></div><p className="text-xs font-bold text-slate-400">برای این هفته هنوز بازی ثبت نشده است.</p></div>}</section>
    <div className="rounded-2xl border border-amber-300/10 bg-amber-300/[.04] px-4 py-3 text-[9px] text-slate-500 leading-5">برنامه روی صفحه بر اساس قرعه رسمی نیم‌فصل اول است؛ نتایج واقعی مسابقات حفظ می‌شود و بازی‌های ناقص با برنامه رسمی تکمیل می‌شوند.</div>
  </div></main>;
}
