"use client";

import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, CalendarDays, ChevronLeft, Home, Medal, RefreshCw, Repeat2, Table2, Trophy, Tv, UserRound, WifiOff } from "lucide-react";
import Link from "next/link";

const tehranDate = (offset = 0) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Tehran" }).format(new Date(Date.now() + offset * 86400000));
const fa = (value) => String(value ?? "").replace(/[0-9]/g, (d) => "۰۱۲۳۴۵۶۷۸۹"[d]);
const liveStatuses = ["1H", "HT", "2H", "ET", "P", "BT", "LIVE"];
const finishedStatuses = ["FT", "AET", "PEN"];
const reasonText = {
  CONFIG_ERROR: "کلید اتصال API فوتبال در Production تنظیم نشده است.",
  AUTH_ERROR: "کلید API فوتبال نامعتبر است یا دسترسی آن رد شده است.",
  RATE_LIMIT: "سقف درخواست API فوتبال پر شده؛ کمی بعد دوباره تلاش کنید.",
  UPSTREAM_ERROR: "سرویس API فوتبال موقتاً پاسخ نمی‌دهد.",
  NETWORK_ERROR: "سرور FOT10 نتوانسته به سرویس فوتبال وصل شود.",
};

function Team({ name, logo, align = "start" }) { return <div className={`flex min-w-0 items-center gap-2 ${align === "end" ? "justify-end text-right" : ""}`}><div className="grid h-11 w-11 shrink-0 place-items-center overflow-hidden rounded-2xl bg-white/[.06] ring-1 ring-white/10 shadow-inner">{logo ? <img src={logo} alt="" className="h-9 w-9 object-contain" /> : <span className="text-sm font-black text-slate-400">{name?.slice(0, 1) || "?"}</span>}</div><span className="truncate text-[12px] font-black leading-5 text-slate-100">{name || "—"}</span></div>; }
function MatchCard({ match }) { const live = liveStatuses.includes(match.statusShort); const finished = finishedStatuses.includes(match.statusShort); const time = match.date ? new Intl.DateTimeFormat("fa-IR", { timeZone: "Asia/Tehran", hour: "2-digit", minute: "2-digit" }).format(new Date(match.date)) : "—"; return <Link href={`/matches/${match.id}`} className="glass card group block overflow-hidden p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-emerald-300/20 active:scale-[.985]"><div className="mb-4 flex items-center justify-between gap-3 text-[9px] font-bold text-slate-500"><span className="truncate">{match.country || "فوتبال"} <span className="px-1 text-slate-700">•</span> {match.league || "مسابقه"}</span>{live ? <span className="live-pulse shrink-0 rounded-full bg-emerald-400/10 px-2.5 py-1 font-black text-emerald-300">● زنده {match.elapsed ? fa(`${match.elapsed}'`) : ""}</span> : <span className="shrink-0">{finished ? "پایان" : fa(time)}</span>}</div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2"><Team name={match.home} logo={match.homeLogo} /><div className="min-w-[70px] text-center">{match.homeScore != null || match.awayScore != null ? <div className="text-xl font-black tracking-tight">{fa(match.homeScore ?? 0)} <span className="text-slate-600">-</span> {fa(match.awayScore ?? 0)}</div> : <div className="text-base font-black">{fa(time)}</div>}<div className={`mt-1 text-[8px] font-bold ${live ? "text-emerald-300" : "text-slate-600"}`}>{match.status || "برنامه‌ریزی‌شده"}</div></div><Team name={match.away} logo={match.awayLogo} align="end" /></div><div className="mt-4 flex items-center justify-between border-t border-white/5 pt-3 text-[9px] font-bold text-slate-600"><span>مرکز مسابقه</span><ChevronLeft size={14} className="transition-transform group-hover:-translate-x-1" /></div></Link>; }

export default function HomePage() {
  const [day, setDay] = useState(0); const [matches, setMatches] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(null); const [diagnostic, setDiagnostic] = useState(null); const [checking, setChecking] = useState(false); const date = useMemo(() => tehranDate(day), [day]);

  const checkConnection = async () => { setChecking(true); try { const response = await fetch("/api/football/status", { cache: "no-store" }); const json = await response.json(); setDiagnostic(json); return json; } catch { const json = { ok: false, code: "NETWORK_ERROR", message: "بررسی وضعیت اتصال ناموفق بود." }; setDiagnostic(json); return json; } finally { setChecking(false); } };
  const load = async (silent = false) => { if (silent) setRefreshing(true); else setLoading(true); setError(null); try { const res = await fetch(`/api/football/fixtures?date=${date}`, { cache: "no-store" }); const json = await res.json(); if (!res.ok || !json.ok) { const detail = json.error?.message || json.error || "خطا در دریافت مسابقات"; const err = new Error(detail); err.code = json.error?.code || "API_ERROR"; throw err; } setMatches(Array.isArray(json.matches) ? json.matches : []); setDiagnostic({ ok: true, code: "OK", provider: json.provider }); } catch (e) { setMatches([]); setError({ code: e.code || "API_ERROR", message: e.message || "ارتباط با سرویس فوتبال برقرار نشد" }); await checkConnection(); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { load(false); }, [date]);
  useEffect(() => { const id = setInterval(() => load(true), 30000); return () => clearInterval(id); }, [date]);

  const liveCount = matches.filter((m) => liveStatuses.includes(m.statusShort)).length; const leagueCount = new Set(matches.map((m) => `${m.country}|${m.league}`)).size;
  const quickNav = [["لیگ‌ها", Trophy, "/leagues"], ["برنامه بازی‌ها", CalendarDays, "/matches"], ["آمار و ارقام", BarChart3, "/stats"], ["جدول لیگ‌ها", Table2, "/leagues"], ["برترین‌های ماه", Medal, "/players"], ["نقل‌وانتقالات", Repeat2, "/transfers"]];
  const nav = [["خانه", Home, "/"], ["بازی‌ها", Tv, "/matches"], ["لیگ‌ها", Trophy, "/leagues"], ["حساب من", UserRound, "/account"]];

  return <main className="fot-container pb-28"><header className="relative overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-[#111b2d] via-[#0b1220] to-[#080c15] p-5 shadow-2xl"><div className="absolute -left-10 -top-16 h-40 w-40 rounded-full bg-yellow-400/10 blur-3xl" /><div className="absolute -right-12 bottom-0 h-40 w-40 rounded-full bg-emerald-400/10 blur-3xl" /><div className="relative flex items-center justify-between gap-4"><Link href="/" className="min-w-0"><div className="flex items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-yellow-300/20 bg-yellow-300/10 text-2xl font-black italic text-yellow-300 shadow-lg">10</div><div><div className="text-2xl font-black tracking-tight">FOT<span className="text-emerald-400">10</span></div><p className="mt-0.5 text-[9px] font-bold text-slate-500">نبض فوتبال، لحظه‌به‌لحظه</p></div></div></Link><button onClick={() => load(true)} disabled={refreshing} className="glass touch-target grid h-11 w-11 shrink-0 place-items-center rounded-2xl" aria-label="به‌روزرسانی"><RefreshCw size={17} className={refreshing ? "animate-spin" : ""} /></button></div><div className="relative mt-5 flex items-end justify-between gap-4"><div><p className="mb-1 text-[10px] font-black text-yellow-300">GOLDEN 10</p><h1 className="text-[25px] font-black leading-tight">همه فوتبال، یک‌جا</h1><p className="mt-2 max-w-[290px] text-[10px] leading-5 text-slate-400">نتایج زنده، مسابقات، لیگ‌ها و آمار کامل بازیکنان؛ شماره ۱۰ امضای برند FOT10 است.</p></div><div className="select-none text-[86px] font-black italic leading-none text-white/[.035]">10</div></div></header>
  <section className="mt-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-black">دسترسی سریع</h2><p className="mt-1 text-[9px] font-bold text-slate-600">همه بخش‌های مهم FOT10</p></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[8px] font-black text-emerald-300">FOT10</span></div><div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">{quickNav.map(([label, Icon, href], index) => <Link key={label} href={href} className="group relative overflow-hidden rounded-2xl border border-white/10 bg-white/[.035] p-3.5 shadow-lg transition-all duration-200 hover:-translate-y-0.5 hover:border-emerald-300/25 hover:bg-white/[.06] active:scale-[.98]"><div className="absolute -left-5 -top-5 h-16 w-16 rounded-full bg-emerald-400/5 blur-2xl" /><div className="relative flex items-center gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl border ${index === 0 ? "border-yellow-300/20 bg-yellow-300/10 text-yellow-300" : "border-emerald-300/10 bg-emerald-400/10 text-emerald-300"}`}><Icon size={19}/></div><div className="min-w-0"><div className="truncate text-[11px] font-black text-slate-100">{label}</div><div className="mt-1 text-[8px] font-bold text-slate-600">مشاهده</div></div><ChevronLeft size={14} className="mr-auto shrink-0 text-slate-700 transition-transform group-hover:-translate-x-1" /></div></Link>)}</div></section>
  <section className="mt-4 grid grid-cols-3 gap-2"><div className="glass rounded-2xl p-3 text-center"><div className="text-lg font-black text-emerald-300">{fa(liveCount)}</div><div className="text-[9px] font-bold text-slate-600">زنده</div></div><div className="glass rounded-2xl p-3 text-center"><div className="text-lg font-black">{fa(matches.length)}</div><div className="text-[9px] font-bold text-slate-600">بازی امروز</div></div><div className="glass rounded-2xl p-3 text-center"><div className="text-lg font-black">{fa(leagueCount)}</div><div className="text-[9px] font-bold text-slate-600">لیگ</div></div></section>
  <section className="mt-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">مرکز مسابقات</h2><p className="mt-1 text-[10px] font-bold text-slate-600">بازی‌ها و نتایج فوتبال</p></div><Activity size={19} className="text-emerald-400" /></div><div className="mb-4 grid grid-cols-3 gap-2">{[["دیروز", -1], ["امروز", 0], ["فردا", 1]].map(([label, value]) => <button key={value} onClick={() => setDay(value)} className={`touch-target rounded-2xl px-3 py-3 text-xs font-black transition ${day === value ? "bg-emerald-400 text-slate-950 shadow-lg shadow-emerald-400/10" : "glass text-slate-400"}`}>{label}</button>)}</div>
    {error && <div className="mb-4 overflow-hidden rounded-2xl border border-red-400/20 bg-red-400/10"><div className="flex items-start gap-3 p-4"><WifiOff size={19} className="mt-0.5 shrink-0 text-red-300" /><div className="min-w-0"><div className="text-sm font-black text-red-100">اتصال داده فوتبال مشکل دارد</div><p className="mt-1 text-[10px] leading-5 text-red-200/80">{reasonText[error.code] || error.message}</p><div className="mt-2 inline-flex rounded-lg bg-black/20 px-2 py-1 font-mono text-[9px] text-red-200">کد: {error.code}</div></div></div>{diagnostic && <div className="border-t border-red-300/10 px-4 py-3 text-[9px] font-bold text-red-100/70">{diagnostic.ok ? `اتصال سالم است • ${diagnostic.provider}` : reasonText[diagnostic.code] || diagnostic.message}</div>}<div className="flex gap-2 border-t border-red-300/10 p-3"><button onClick={checkConnection} disabled={checking} className="rounded-xl bg-white/10 px-3 py-2 text-[10px] font-black text-white">{checking ? "در حال بررسی…" : "بررسی اتصال"}</button><button onClick={() => load(false)} className="rounded-xl bg-emerald-400 px-3 py-2 text-[10px] font-black text-slate-950">تلاش دوباره</button></div></div>}
    {loading ? <div className="glass rounded-2xl p-10 text-center text-xs font-bold text-slate-500">در حال دریافت مسابقات واقعی…</div> : matches.length === 0 ? <div className="glass rounded-2xl p-10 text-center"><div className="text-sm font-black">برای این روز مسابقه‌ای پیدا نشد</div><p className="mt-2 text-[10px] font-bold text-slate-600">اگر اتصال سالم باشد، یعنی برای این تاریخ داده‌ای از سرویس فوتبال برنگشته است.</p></div> : <div className="space-y-3">{matches.map((match) => <MatchCard key={match.id} match={match} />)}</div>}
  </section><nav className="fixed inset-x-0 bottom-0 z-40 border-t border-white/5 bg-[#05070d]/90 px-2 py-2 backdrop-blur-xl"><div className="mx-auto grid max-w-xl grid-cols-4 gap-1">{nav.map(([label, Icon, href]) => <Link key={href} href={href} className={`flex flex-col items-center gap-1 rounded-xl px-2 py-2 text-[9px] font-bold transition ${href === "/" ? "text-emerald-300" : "text-slate-500 hover:text-slate-300"}`}><Icon size={17}/><span>{label}</span></Link>)}</div></nav></main>;
}
