"use client";

import { BarChart3, ChevronLeft, Home, Medal, Repeat2, Settings, Shield, Table2, Trophy, Tv, UserRound } from "lucide-react";
import Link from "next/link";
import HomeMatchdayHub from "./components/HomeMatchdayHub";
import HomeNews from "./components/HomeNews";

export default function HomePage() {
  const quickNav = [["لیگ‌ها", Trophy, "/leagues"], ["تیم ملی", Shield, "/national-teams"], ["آمار و ارقام", BarChart3, "/stats"], ["جدول لیگ‌ها", Table2, "/leagues"], ["برترین‌های ماه", Medal, "/players"], ["نقل‌وانتقالات", Repeat2, "/transfers"], ["تنظیمات", Settings, "/settings"]];
  const nav = [["خانه", Home, "/"], ["بازی‌ها", Tv, "/matches"], ["لیگ‌ها", Trophy, "/leagues"], ["حساب من", UserRound, "/account"]];

  return <main className="fot-container pb-28"><header className="relative overflow-hidden rounded-[28px] border border-white/10 bg-gradient-to-br from-[#111b2d] via-[#0b1220] to-[#080c15] p-5 shadow-2xl"><div className="absolute -left-10 -top-16 h-40 w-40 rounded-full bg-yellow-400/10 blur-3xl" /><div className="absolute -right-12 bottom-0 h-40 w-40 rounded-full bg-emerald-400/10 blur-3xl" /><div className="relative flex items-center justify-between gap-4"><Link href="/" className="min-w-0"><div className="flex items-center gap-3"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl border border-yellow-300/20 bg-yellow-300/10 text-2xl font-black italic text-yellow-300 shadow-lg">10</div><div><div className="text-2xl font-black tracking-tight">FOT<span className="text-emerald-400">10</span></div><p className="mt-0.5 text-[9px] font-bold text-slate-500">نبض فوتبال، لحظه‌به‌لحظه</p></div></div></Link></div><div className="relative mt-5 flex items-end justify-between gap-4"><div><p className="mb-1 text-[10px] font-black text-yellow-300">GOLDEN 10</p><h1 className="text-[25px] font-black leading-tight">همه فوتبال، یک‌جا</h1><p className="mt-2 max-w-[310px] text-[10px] leading-5 text-slate-400">خبرهای روز، لیگ‌ها، آمار، بازیکنان و مهم‌ترین اتفاقات فوتبال ایران و جهان.</p></div><div className="select-none text-[86px] font-black italic leading-none text-white/[.035]">10</div></div></header>

  <HomeMatchdayHub />
  <HomeNews />

  <section className="mt-4"><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-black">دسترسی سریع</h2><p className="mt-1 text-[9px] font-bold text-slate-600">بخش‌های اصلی FOT10</p></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[8px] font-black text-emerald-300">FOT10</span></div><div className="grid grid-cols-2 gap-2.5 sm:grid-cols-3">{quickNav.map(([label, Icon, href], index) => <Link key={label} href={href} className="group relative overflow-hidden rounded-2xl border border-white/10 bg-white/[.035] p-3.5 shadow-lg transition-all duration-200 hover:-translate-y-0.5 hover:border-emerald-300/25 hover:bg-white/[.06] active:scale-[.98]"><div className="absolute -left-5 -top-5 h-16 w-16 rounded-full bg-emerald-400/5 blur-2xl" /><div className="relative flex items-center gap-3"><div className={`grid h-11 w-11 shrink-0 place-items-center rounded-xl border ${label === "تنظیمات" ? "border-cyan-300/20 bg-cyan-400/10 text-cyan-300" : index === 0 ? "border-yellow-300/20 bg-yellow-300/10 text-yellow-300" : "border-emerald-300/10 bg-emerald-400/10 text-emerald-300"}`}><Icon size={19}/></div><div className="min-w-0"><div className="truncate text-[11px] font-black text-slate-100">{label}</div><div className="mt-1 text-[8px] font-bold text-slate-600">{label === "تنظیمات" ? "شخصی‌سازی اپ" : "مشاهده"}</div></div><ChevronLeft size={14} className="mr-auto shrink-0 text-slate-700 transition-transform group-hover:-translate-x-1" /></div></Link>)}</div></section>

  <nav className="fixed inset-x-0 bottom-0 z-40 border-t border-white/5 bg-[#05070d]/90 px-2 py-2 backdrop-blur-xl"><div className="mx-auto grid max-w-xl grid-cols-4 gap-1">{nav.map(([label, Icon, href]) => <Link key={href} href={href} className={`flex flex-col items-center gap-1 rounded-xl px-2 py-2 text-[9px] font-bold transition ${href === "/" ? "text-emerald-300" : "text-slate-500 hover:text-slate-300"}`}><Icon size={17}/><span>{label}</span></Link>)}</div></nav></main>;
}
