"use client";

import { useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import { ArrowLeftRight, Shield, Swords, Trophy, Target, TrendingUp, Loader2, History, Zap } from "lucide-react";
import { teamName } from "../lib/team-identity";

const LEAGUES = { iran: 195, "j1-league": 98, "k-league-1": 292, "saudi-pro-league": 307, "qatar-stars-league": 305, "uae-pro-league": 301, "chinese-super-league": 169, "a-league": 188, "premier-league": 39, laliga: 140, bundesliga: 78, "serie-a": 135, "ligue-1": 61, eredivisie: 88, "primeira-liga": 94, "super-lig": 203, mls: 253, "liga-mx": 262, brasileirao: 71, "liga-profesional": 128 };

function flatRows(payload) { return (payload?.data || []).flatMap((item) => item?.league?.standings?.flat?.() || []).filter(Boolean); }
function score(a, b, lowerBetter = false) { const x = Number(a || 0), y = Number(b || 0); if (x === y) return "draw"; return lowerBetter ? (x < y ? "home" : "away") : (x > y ? "home" : "away"); }
function Metric({ label, left, right, icon: Icon, lowerBetter = false }) { const winner = score(left, right, lowerBetter); return <div className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="mb-2 flex items-center justify-center gap-1.5 text-[9px] font-bold text-slate-500"><Icon size={12}/>{label}</div><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 text-center"><b className={winner === "home" ? "text-cyan-300" : "text-slate-300"}>{left ?? "—"}</b><span className="text-[8px] text-slate-600">VS</span><b className={winner === "away" ? "text-cyan-300" : "text-slate-300"}>{right ?? "—"}</b></div></div>; }

function formFor(matches, teamId) {
  return matches.filter(m => Number(m.homeId) === Number(teamId) || Number(m.awayId) === Number(teamId)).sort((a,b) => new Date(b.date || 0) - new Date(a.date || 0)).slice(0,5).map(m => {
    const home = Number(m.homeId) === Number(teamId); const gf = Number(home ? m.homeScore : m.awayScore); const ga = Number(home ? m.awayScore : m.homeScore);
    return { result: gf > ga ? "W" : gf < ga ? "L" : "D", gf: Number.isFinite(gf) ? gf : 0, ga: Number.isFinite(ga) ? ga : 0, date: m.date, opponent: home ? m.away : m.home };
  });
}

export default function TeamComparisonPro() {
  const pathname = usePathname();
  const [teams, setTeams] = useState([]); const [matches, setMatches] = useState([]); const [loading, setLoading] = useState(true); const [matchesLoading, setMatchesLoading] = useState(false); const [leftId, setLeftId] = useState(""); const [rightId, setRightId] = useState("");
  const slug = pathname?.split("/").filter(Boolean).pop(); const league = LEAGUES[slug]; const season = league === 195 ? 2026 : new Date().getFullYear();

  useEffect(() => { let alive = true; if (!league) { setLoading(false); return; } fetch(`/api/football/standings?league=${league}&season=${season}`, { cache: "no-store" }).then(r => r.json()).then(payload => { if (!alive || !payload?.ok) return; const rows = flatRows(payload); setTeams(rows); if (rows.length > 1) { setLeftId(String(rows[0].team?.id || "")); setRightId(String(rows[1].team?.id || "")); } }).catch(() => {}).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [pathname, league, season]);

  useEffect(() => { let alive = true; if (!league || !leftId || !rightId) return; setMatchesLoading(true); fetch(`/api/football/fixtures?league=${league}&season=${season}`, { cache: "no-store" }).then(r => r.json()).then(payload => { if (!alive || !payload?.ok) return; setMatches(Array.isArray(payload.matches) ? payload.matches : []); }).catch(() => {}).finally(() => alive && setMatchesLoading(false)); return () => { alive = false; }; }, [league, season, leftId, rightId]);

  const left = useMemo(() => teams.find(x => String(x.team?.id) === String(leftId)), [teams, leftId]); const right = useMemo(() => teams.find(x => String(x.team?.id) === String(rightId)), [teams, rightId]);
  const stat = (row, key) => row?.all?.[key] ?? 0; const goalsFor = row => row?.all?.goals?.for ?? 0; const goalsAgainst = row => row?.all?.goals?.against ?? 0; const goalDiff = row => Number(goalsFor(row)) - Number(goalsAgainst(row));
  const leftForm = useMemo(() => formFor(matches, leftId), [matches, leftId]); const rightForm = useMemo(() => formFor(matches, rightId), [matches, rightId]);
  const h2h = useMemo(() => matches.filter(m => { const a = Number(m.homeId), b = Number(m.awayId); return (a === Number(leftId) && b === Number(rightId)) || (a === Number(rightId) && b === Number(leftId)); }).filter(m => m.homeScore !== null && m.awayScore !== null).sort((a,b) => new Date(b.date || 0) - new Date(a.date || 0)).slice(0,5), [matches, leftId, rightId]);
  const formStats = form => ({ wins: form.filter(x => x.result === "W").length, draws: form.filter(x => x.result === "D").length, losses: form.filter(x => x.result === "L").length, gf: form.reduce((s,x) => s+x.gf,0), ga: form.reduce((s,x) => s+x.ga,0) });
  const lf = formStats(leftForm), rf = formStats(rightForm);
  const h2hScore = h2h.reduce((s,m) => { const home = Number(m.homeId) === Number(leftId); const hg = Number(m.homeScore), ag = Number(m.awayScore); return { ...s, left: s.left + (home ? hg > ag : ag > hg ? 1 : 0), right: s.right + (home ? ag > hg : hg > ag ? 1 : 0), draw: s.draw + (hg === ag ? 1 : 0) }; }, { left:0, right:0, draw:0 });

  if (loading) return <section className="mx-auto max-w-5xl rounded-2xl border border-cyan-300/10 bg-cyan-400/[.035] p-4 text-center text-[10px] text-slate-500"><Loader2 size={15} className="mx-auto mb-2 animate-spin text-cyan-300"/>در حال دریافت جدول برای مقایسه تیم‌ها…</section>;
  if (teams.length < 2) return null;
  return <section className="mx-auto max-w-5xl rounded-2xl border border-cyan-300/10 bg-cyan-400/[.035] p-3 shadow-xl shadow-cyan-950/10 sm:p-4">
    <div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><ArrowLeftRight size={16} className="text-cyan-300"/><h2 className="text-sm font-black text-white">مقایسه حرفه‌ای تیم‌ها</h2></div><span className="text-[8px] text-slate-500">FOT10 TEAM COMPARISON PRO+</span></div>
    <div className="grid gap-2 sm:grid-cols-[1fr_auto_1fr] sm:items-end"><label className="text-[9px] font-bold text-slate-500">تیم اول<select value={leftId} onChange={e => setLeftId(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-xs font-bold text-white outline-none"><option value="">انتخاب تیم</option>{teams.map(x => <option key={x.team?.id} value={x.team?.id}>{teamName(x.team?.name)}</option>)}</select></label><div className="hidden h-10 w-10 place-items-center rounded-full border border-cyan-300/15 bg-cyan-300/[.05] text-[9px] font-black text-cyan-300 sm:grid">VS</div><label className="text-[9px] font-bold text-slate-500">تیم دوم<select value={rightId} onChange={e => setRightId(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-slate-950 px-3 py-2.5 text-xs font-bold text-white outline-none"><option value="">انتخاب تیم</option>{teams.map(x => <option key={x.team?.id} value={x.team?.id}>{teamName(x.team?.name)}</option>)}</select></label></div>
    {left && right && <>
      <div className="mt-3 grid grid-cols-2 gap-2 text-center">{[left,right].map(row => <div key={row.team?.id} className="rounded-xl border border-white/5 bg-black/20 p-3"><div className="text-sm font-black truncate">{teamName(row.team?.name)}</div><div className="mt-1 text-[9px] text-cyan-300">{row.points ?? 0} امتیاز · رتبه {row.rank ?? "—"}</div></div>)}</div>
      <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="برد" left={stat(left,"win")} right={stat(right,"win")} icon={Trophy}/><Metric label="گل زده" left={goalsFor(left)} right={goalsFor(right)} icon={Swords}/><Metric label="گل خورده" left={goalsAgainst(left)} right={goalsAgainst(right)} icon={Shield} lowerBetter/><Metric label="تفاضل گل" left={goalDiff(left)} right={goalDiff(right)} icon={Target}/></div>
      <div className="mt-3 rounded-xl border border-white/5 bg-black/15 p-3"><div className="mb-2 flex items-center justify-center gap-2 text-[9px] font-black text-slate-400"><Zap size={12} className="text-cyan-300"/> فرم ۵ بازی اخیر</div><div className="grid grid-cols-2 gap-3"><div className="text-center"><div className="mb-1 text-[9px] font-bold text-slate-300">{teamName(left.team?.name)}</div><div className="flex justify-center gap-1">{leftForm.map((x,i)=><span key={i} title={`${x.opponent}: ${x.gf}-${x.ga}`} className={`grid h-6 w-6 place-items-center rounded-full text-[8px] font-black ${x.result === "W" ? "bg-emerald-400/20 text-emerald-300" : x.result === "D" ? "bg-amber-400/20 text-amber-300" : "bg-rose-400/20 text-rose-300"}`}>{x.result}</span>)}{!leftForm.length && <span className="text-[8px] text-slate-600">داده‌ای نیست</span>}</div><div className="mt-1 text-[8px] text-slate-500">{lf.wins} برد · {lf.draws} مساوی · {lf.losses} باخت · {lf.gf} گل</div></div><div className="text-center"><div className="mb-1 text-[9px] font-bold text-slate-300">{teamName(right.team?.name)}</div><div className="flex justify-center gap-1">{rightForm.map((x,i)=><span key={i} title={`${x.opponent}: ${x.gf}-${x.ga}`} className={`grid h-6 w-6 place-items-center rounded-full text-[8px] font-black ${x.result === "W" ? "bg-emerald-400/20 text-emerald-300" : x.result === "D" ? "bg-amber-400/20 text-amber-300" : "bg-rose-400/20 text-rose-300"}`}>{x.result}</span>)}{!rightForm.length && <span className="text-[8px] text-slate-600">داده‌ای نیست</span>}</div><div className="mt-1 text-[8px] text-slate-500">{rf.wins} برد · {rf.draws} مساوی · {rf.losses} باخت · {rf.gf} گل</div></div></div></div>
      <div className="mt-3 rounded-xl border border-white/5 bg-black/15 p-3"><div className="mb-2 flex items-center justify-center gap-2 text-[9px] font-black text-slate-400"><History size={12} className="text-cyan-300"/> رودررو (H2H) · {h2h.length} بازی</div>{matchesLoading ? <div className="flex items-center justify-center gap-2 py-2 text-[8px] text-slate-600"><Loader2 size={12} className="animate-spin"/> در حال دریافت نتایج</div> : h2h.length ? <><div className="mb-2 flex justify-center gap-4 text-[8px] text-slate-500"><span>{teamName(left.team?.name)} <b className="text-cyan-300">{h2hScore.left}</b></span><span>مساوی <b className="text-amber-300">{h2hScore.draw}</b></span><span><b className="text-cyan-300">{h2hScore.right}</b> {teamName(right.team?.name)}</span></div><div className="space-y-1">{h2h.map((m,i)=><div key={m.id || i} className="grid grid-cols-[1fr_auto_1fr] items-center gap-2 rounded-lg bg-black/20 px-2 py-1.5 text-[8px]"><span className="truncate text-right text-slate-300">{teamName(m.home)}</span><b className="text-cyan-300">{m.homeScore} - {m.awayScore}</b><span className="truncate text-slate-300">{teamName(m.away)}</span></div>)}</div></> : <div className="py-2 text-center text-[8px] text-slate-600">تقابل ثبت‌شده‌ای در داده فعلی پیدا نشد</div>}</div>
    </>}
  </section>;
}
