export const NATIONAL_TEAMS = [
  { slug: "iran", name: "ایران", country: "ایران", id: 22 },
  { slug: "japan", name: "ژاپن", country: "ژاپن", id: 12 },
  { slug: "south-korea", name: "کره جنوبی", country: "کره جنوبی", id: 17 },
  { slug: "saudi-arabia", name: "عربستان", country: "عربستان", id: 23 },
  { slug: "qatar", name: "قطر", country: "قطر", id: 156 },
  { slug: "australia", name: "استرالیا", country: "استرالیا", id: 20 },
  { slug: "france", name: "فرانسه", country: "فرانسه", id: 2 },
  { slug: "england", name: "انگلیس", country: "انگلیس", id: 10 },
  { slug: "spain", name: "اسپانیا", country: "اسپانیا", id: 9 },
  { slug: "germany", name: "آلمان", country: "آلمان", id: 25 },
  { slug: "italy", name: "ایتالیا", country: "ایتالیا", id: 768 },
  { slug: "brazil", name: "برزیل", country: "برزیل", id: 6 },
  { slug: "argentina", name: "آرژانتین", country: "آرژانتین", id: 26 },
  { slug: "portugal", name: "پرتغال", country: "پرتغال", id: 27 },
  { slug: "netherlands", name: "هلند", country: "هلند", id: 1118 },
  { slug: "turkey", name: "ترکیه", country: "ترکیه", id: 34 },
  { slug: "usa", name: "آمریکا", country: "آمریکا", id: 238 },
];
